### ISSUE TITLE
maximizing cygwin (i.e. mintty) to region causes font size to change in terminal

### ISSUE THREAD

**Issue by j-n-f** [digitalcreations/MaxTo#102]
This behaviour is somewhat inconsistent. Sometimes the font size will increase when maximizing to region, sometimes the font shrinks.

Machine details:
* Windows 7 Pro

MaxTo settings:

* MaxTo set to operate only with modifier (passive mode, Shift is modifier)
* Screen evenly divided into 4 regions (one split horizontal, one vertical, natural size and not resized at all after splitting)

Cygwin information:

* mintty 2.1.5 (i686-pc-cygwin)

None of the Cygwin font size settings have changed (either manually, or when the font size changes w.r.t. this issue). Changing the region maximized to has no impact. If the font size increases/decreases when maximized to one region, it exhibits the same behaviour in all of them. In some cases

Under Cygwin's options, I notice some options that point to potential problems:

* Under "Mouse" there is a radio-select for a modifier key (defaults to Shift, like MaxTo)
* Under "Window", there is a radio-select similar to the one for "Mouse" (defaults to Shift, similarly)

I'm not suggesting that this is necessarily a MaxTo bug, but understanding why this happens could be useful.

**Comment by j-n-f** [comment]
Additional observation:

If the window is larger than the region maximized to, the font shrinks when the window shrinks. If the window is smaller than the region maximized to, the font expands.

**Comment by vegardlarsen** [comment]
This seems strange, but I have a guess at what could be happening. Resizing a console window in general is quite the process. If you try to resize a standard `cmd` window you will see that you simply cannot. If you try to maximize a console window, it will only grow vertically.

However, MaxTo uses a technique that will make the window do what you want, by changing the number of rows and columns displayed in the console. To do that, it has to **read** the font size from the console window, and use that to calculate the closest possible window size. That is why a console window may not match the region size exactly, because width and height has to be a multiple of font size.

My guess at what is happening here, is that cygwin somehow supports resizing better than a standard console window, but the interaction with MaxTo's way of resizing is causing the problem. I am guessing that cygwin scales the font up or down to make it match the available width.

I am going to do some experiments on this before releasing the next version to see if there is anything we can do to fix it.

**Comment by vegardlarsen** [comment]
There are quite a few things regarding `mintty` that make this a little difficult:

1. It isn't technically a console window (in the Win32 sense of the word). This means MaxTo's special handling for console windows don't kick in (and it wouldn't work anyhow).
2. When `mintty` has a vertical scrollbar, it somehow calculates its own size without the scrollbar. This manifests itself in two ways:
  - When MaxTo tries to restrict it to a region, the scrollbar comes in addition to its stated size, so the window becomes larger than MaxTo tells it to be.
  - When MaxTo tries to restore it, the window somehow becomes smaller.

If you disable the scrollbar in `mintty`, and instead use Shift+PageUp/PageDn to scroll, it works really well with MaxTo.

There is clearly something wrong here, but I am doubtful this is something that MaxTo can solve. I suggest you go file a bug with mintty to get this fixed.

**Comment by j-n-f** [comment]
I suspect you're correct, but thought it was at least an interesting case. Thanks for looking in to this :)
