### ISSUE TITLE
Windows 10 virtual desktops are not supported

### ISSUE THREAD

**Issue by ghost** [digitalcreations/MaxTo#114]
MaxTo should allow you to switch desktop layouts for each virtual desktop on Windows 10, but as of now it only lets you load on layout per physical monitor.

**Comment by vegardlarsen** [comment]
This is an intriguing idea. In a little more detail, how would you imagine this should work?

**Comment by Win-slow** [comment]
I don't think there's much more to it than that, basically MaxTo currently handles layouts on a per-physical-monitor basis. Windows 10 now supports virtual desktops (the hotkey is WIN+TAB to manage them) so I would expect MaxTo to treat each virtual desktop as if it were a separate physical monitor and allow you to assign a new layout to it. I'm not sure on how MaxTo could remember which desktop is which, but you could probably just track it by the desktop number. That would work fine for me since I personally always put specific windows on virtual desktop #1 and another specific set on virtual desktop #2.

Hope that makes sense, and thanks!

**Comment by nblackburn** [comment]
+1

**Comment by MikeMelendez21** [comment]
I have to bump this.  MaxTo is great, but it is really missing out on the virtual desktop space.  Personally this is how I would see it.

MaxTo should detect the creation of a new virtual desktop and popup/prompt the user to load a profile, define regions, or do nothing.  From that point on MaxTo will retain the specified regions on the specified virtual desktop until said virtual desktop is closed.  

If a user switches to a different virtual desktop, then the regions specified for said virtual desktop is used.  

The settings "Change regions", "Highlight regions" and "Fit all windows" is localized to the current virtual desktop.  Changing regions here can override the ones specified at creation.

All other settings are global across all virtual desktops.  

That would be the bare minimum.  But IMO the important part is creating a new virtual desktop and assigning a profile in the least amount of actions possible.  In that case showing a list of user defined favorite profiles or recent used profiles as buttons on the new desktop creation popup would really help.

**Comment by adoerler** [comment]
Hi,

I've just got an 21:9 Screen and would love to use maxto.net as the LG's Split Screen Software is a little bit limited.
It would be great to have different Profiles per virtual Desktop in Windows 10.

Kind regards
Andreas

**Comment by Leuthcorps** [comment]
This is what I signed up to request. 
I'm running a three screen win10 system and use multiple virtual desktops. Having the ability to set each one to different settings would be amazing.
Also just purchased a license in hopes that this becomes a thing.

**Comment by staeff777** [comment]
I think this is important. The ability of maxto, to work with Win10 Virtual Desktops is a must. A possible idea for Detecting the current Deskop might have https://github.com/m0ngr31/VirtualDesktopManager .

**Comment by vegardlarsen** [comment]
Virtual Desktop support is in the previews of version 2.0.0. See #220 for details on how you can try them out.

I am closing this issue as fixed.
