### ISSUE TITLE
Support installation on offline system

### ISSUE THREAD

**Issue by mattproc** [digitalcreations/MaxTo#123]
The installer hangs for a few minutes on "Downloading .NET Framework 4.5 (web installer)" which is obviously going to fail because there's no internet connection. It eventually proceeds past this section and allows me to click "Next" to apparently begin the actual installation but that eventually fails with "MaxTo setup ended prematurely because of an error. Your system has not been modified (etc)"

Can you provide a version that doesn't require an internet connection?

**Comment by vegardlarsen** [comment]
Since the .NET Framework is so large, we will not be bundling it with the installer. [Here](https://www.microsoft.com/en-us/download/details.aspx?id=42642) is an offline installer for .NET Framework 4.5.2 that should work on your machine.

Install the .NET Framework first, and MaxTo's install should proceed just fine.
