### ISSUE TITLE
Keyboard Shortcuts don't work?

### ISSUE THREAD

**Issue by Vaccano** [digitalcreations/MaxTo#124]
I have to think I am doing something wrong.  But I watched the video and it says to do ctrl + start + arrow key to move between regions.

But that does not work.  (Just sends control + arrow to the application.)

I also tried control + start + page up and it was similarly non functional.

**What am I missing?**

(Note: Shift + drag and drop works fine)

**Comment by vegardlarsen** [comment]
@Vaccano Ooh, we may not have updated the video since the upgrade to Windows 10. That is definitely something we have to fix.

The shortcut keys changed because Windows 10 started using the same ones as we did. They are now Windows+NumPad keys by default (remember to have NumLock on). You can change this if you'd like, but it will probably be hard finding other keys that make sense and are available.

**Comment by Vaccano** [comment]
Sweet!  Thanks!
