### ISSUE TITLE
Minimum region width too large?

### ISSUE THREAD

**Issue by mgomezch** [digitalcreations/MaxTo#129]
Hi!  I’d like to use MaxTo to prevent windows maximizing under an always-on-top panel I use (GKrellM, specifically).  The region occupied by this panel is quite narrow, and this is intentional; I want to have it always present on the screen, but not take up too much space.

![maxto-report-panel](https://cloud.githubusercontent.com/assets/774845/12687840/8291414e-c6a4-11e5-9c94-8b28b821acc8.png)

(In that image, the large Chrome window is not maximized; it’s sized manually to fit the space onto which I’d like it to maximize.)

My issue is that the region setup view does not seem to allow widths smaller than that of the Split/Remove buttons.  This makes sense, of course, as collapsing the buttons may make them unusable, but this also unfortunately seems to prevent defining a region with the size I need.

![maxto-report-buttons](https://cloud.githubusercontent.com/assets/774845/12687853/998d15c6-c6a4-11e5-80ec-2dbee4a2d255.png)

Is it possible to somehow work around this?  Maybe editing the region profiles configuration file directly?  (Where is it, though?)

Alternatively, is there some way to define a set of regions that don’t cover the entire screen?  I really have no interest in maximizing something in the small region where I’d place the always-on-top panel, so it’d be enough for me to have just the large region on the left, and just leave the space on the right unused.  I don’t know if your product supports this, though.

I’m on Windows 10, and the width of my panel is 72 pixels on a 1920×1080 total resolution.

Cheers!

**Comment by vegardlarsen** [comment]
Both yes and no. The minimum region width is limited by the minimum width of a bordered window in Windows. It is not a value I will be changing, because that would be very strange for other windows.

However, you **may** be able to get around this. I haven't tested this, and I cannot guarantee that it will work. Find the `user.config` file by rummaging about `%LocalAppData%\Digital_Creations_AS\MaxTo.exe_<some garbage>\<version>`. This is the file that contains your regions.

Find the setting named `RegionConfiguration`. Find the monitor section that this is about:

```xml
<Monitor Name="\\.\DISPLAY1" Primary="true">
    <Region IsSplit="true" Orientation="Vertical" SplitterDistance="0.5">
        <Region IsSplit="false" Placement="1" />
        <Region IsSplit="false" Placement="2" />
    </Region>
</Monitor>
```

`SplitterDistance` is the relative distance to the splitter. So to calculate a set number of pixels on the right, the formula is: `1 - (size of region / width of screen)`

This should give you a number somewhere around 0.9-1.0. Restart MaxTo. If I am not mistaken, this should load correctly. If you change the regions (or maybe even the options) inside MaxTo, your changes will disappear.

Best of luck, and please let me know if this works for you.

**Comment by mgomezch** [comment]
It worked perfectly!  Thanks!
