### ISSUE TITLE
Dragging to top screen edge to maximise doesn't work with start bar at the top

### ISSUE THREAD

**Issue by nullabletype** [digitalcreations/MaxTo#136]
I have my start bar docked at the top of the screen as I find it more convenient but MaxTo doesn't work properly with dragging windows to the top edge of the screen to maximise. With the start bar at the bottom of the screen it works fine, or without MaxTo running it also works absolutely fine. When its enabled with the start bar at the top of the screen when you release the window stays its current size and the top drag bar is behind the start bar.

This is in Win10.

**Comment by vegardlarsen** [comment]
First let me apologize for not getting back to you sooner. I have been on vacation for the last two weeks, so I am just catching up on things now.

Thanks for reporting this. I have confirmed that this also happens on my machine, and I will be looking at how this can be fixed. I don't really know why this happens yet.

**Comment by vegardlarsen** [comment]
First let me apologize for not getting back to you sooner. I have apparently been on vacation for the last 5 years and 3 days.

I have now finally fixed this issue. Instead of nothing happening, MaxTo will now find the region that is closest to the mouse pointer at that point.

The fix will be in the next release of 2.2.0 (may be another beta, who knows). I'll get to that in the next ~5 years or so.
