### ISSUE TITLE
Open app on monitor that launched it? ( No place to ask questions )

### ISSUE THREAD

**Issue by pgorbas** [digitalcreations/MaxTo#138]
The is the feature I want.
**I want application pop-up windows to launch on the same monitor they run from.**

Say I am running 3 instances of Visual Studio, each instance on its own monitor.

When I click control-f for the find popup, i want it to popup on the monitor and visual stuio instance that launched it.

So VS1 on monitor 1, FIND pops up dialog on monitor 1.
So VS1 on monitor 2, FIND pops up dialog on monitor 2.
So VS1 on monitor 3, FIND pops up dialog on monitor 3.

The default behavior is that no matter what monitor the application is on, the pop ups always open on the last monitor the popup was closed on.  So you can have the find popup from vs3 on monitor 3 on monitor 1. 

There was no other way to ask question.  The information is not clear if it addresses this issue.

**Comment by vegardlarsen** [comment]
@pgorbas Thank you for the idea.

This is an area I am reluctant to step into. When Visual Studio (or any other application) opens a window, it specifies where it wants it to show up, with these choices (this is from Windows Forms, `FormStartPosition`):

- center parent
- center screen
- manual
- Windows default location
- Windows default location and size

Overriding (if it is possible) this can have effects that are completely unintended. In the case of Visual Studio 2015, pressing Ctrl+F does not show a popup, but a small search box in the corner of the active source file editor. If I do Ctrl+Shift+F (Find in files) it opens a window. That window opens in the same location it was the last time you used it, so I get why you may want to move this specific window.

However, detecting which windows to move when they open is difficult. The obvious point to hook in is [`HCBT_CREATEWND`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644977(v=vs.85).aspx). This hook will allow you to determine the size of the window when it opens, but there are caveats:

- you have to determine if the window is a dialog window? Probably a combination of window styles can get you there.
- you have to determine if that window should be moved. If it is set to manual positioning, it is probably a bad idea. I haven't been able to figure out what the `FormStartPosition` equivalent would be in the Win32 APIs.
- How should you place the window since you are moving it? Should it now be centered in the parent window? The screen? In the same proportional position on the new screen as the old screen?

I'd be happy to discuss this with you further, but as of now I don't see a way that this can be implemented in a way that is consistent.
