### ISSUE TITLE
Chrome Canary doesn't work with modifier keys

### ISSUE THREAD

**Issue by ryanjkelly** [digitalcreations/MaxTo#148]
The latest version of Chrome Canary (`54.0.2823.0`) does not respond to modifier keys (e.g. `Shift`, `Ctrl`, `Alt`). However, it does work with hotkeys (e.g. `Windows + NumPad4`, `Windows + NumPad6`).

Probably not an issue for the vast majority of users right now, but could be if Chrome stable inherits the change.

**Comment by vegardlarsen** [comment]
@ryanjkelly Thank you for reporting this. Pre-release software is something I really can't support, because it changes so often and quite often reverts behavior before release. I've even had to exclude doing Insider builds of Windows, because it would just be too much work.

If this makes it into Chrome stable, and is still a problem, please comment on this issue so I can have a look at it.
