### ISSUE TITLE
Windows trapped in main-region

### ISSUE THREAD

**Issue by llinfeng** [digitalcreations/MaxTo#150]
Using the following monitor profile, all the windows that are moved into Monitor 3 shall get trapped there. All the movement actions are not working. Could you solve this bug?

![regions](https://cloud.githubusercontent.com/assets/5890407/17868975/2864a026-687f-11e6-86d5-4a563dae4b94.png)

And, unless I have Monitor 4 vertically split and move windows first to the lower portion of Monitor 4, I don't be able to send windows to Monitor 3. When activating the move-window-right motion, windows can at best loop from 2-1-4.

Is this a known bug? Please advise!

All the best, 

-Linfeng

**Comment by vegardlarsen** [comment]
Currently, this is implemented rather poorly. I will be looking at better algorithms for determining which window is to the left of another window.

The problem is that it is using the vertical midpoint of the region when it searches for regions to the right, and there are no regions there. Same goes for searching upwards, it uses the horizontal midpoint of the region, and there are no regions above it.

I am thinking in the future this will instead use a "shared border" policy. Look at regions that are adjacent in the direction we are looking (basically having a shared border with the region the window is currently in).
