### ISSUE TITLE
Regions resetting on nVidia driver update

### ISSUE THREAD

**Issue by killroy42** [digitalcreations/MaxTo#154]
After an nVidia driver update which did not require a reboot, regions are reset to default. It appears the "primary" monitor remains, but this helps little as I don't really use that one and primarily have maxTo to manage my 4k, 49" secondary.

**Comment by vegardlarsen** [comment]
If you set up your regions again, are they persisted then?

This could be because the monitor changed its number in Windows, which is a particularly annoying feature of MaxTo as it stands today.

**Comment by killroy42** [comment]
I've saved my configs so I can restore them more easily. Although that has it's own issues as the main/alternate require separate trips into the settings and load screens and it loads per monitor, so that's 4 operations with about 10 clicks each, lol. So far, each nVidia driver update resets my secondary monitor (not my primary). But since my secondary is my large 4k, which I got maxTo for in the first place, that's a major issue.

**Comment by killroy42** [comment]
Hey,

Is there any way to auto-load a set of profiles? (since they are separate
by monitor.

It still resets every time there is any hiccup, such as a nVidia driver
update, or any kinda of visual glitch.

Cheers,
Sven

**Comment by vegardlarsen** [comment]
Horribly sorry for the slow response on this, @killroy42. This is not currently possible.

**Comment by killroy42** [comment]
It also happens when removing and re-adding the driver from Device Manager. Any news on this?

**Comment by vegardlarsen** [comment]
I think this will work a lot better in version 2.0.0, see issue #220 for details of how to test this. Please let me know in this thread if the issue is not fixed.

**Comment by killroy42** [comment]
Last driver update did not reset my MaxTo regions, YEY! Thanks!

**Comment by 57thkafka** [comment]
This has just saved me from unneccesarily annoying the programmers. Nvidia 430.64 just reset my regions!

**Comment by vegardlarsen** [comment]
This is likely due to the driver update changing the identifiers of your monitors. MaxTo tries to use the monitor serial number, if that is not available it constructs a "location identifier" based on the video card the monitor is connected to. If the video card gets a new id as part of a driver update, MaxTo won't be able to recognize that monitor's "location" anymore, and will effectively not find the regions.

PS! The monitor settings (incl. regions) are still saved on your drive, just with a path that MaxTo thinks apply to a different monitor.
