### ISSUE TITLE
Window size shrinks on a high dpi screen

### ISSUE THREAD

**Issue by baabo** [digitalcreations/MaxTo#157]
I found an issue that appears at least on my Windows 10 installation with 2.0 dpi scaling. The issue appears when I move a application to a region, and then move it out of the region by dragging the application from the title bar. The size of the window changes to 1/4 what it was before, when it should not change at all. The shrinking continues until the application window can't get any smaller.

I hope you can reproduce this. I can provide additional information if you need. Thank you.

**Comment by vegardlarsen** [comment]
Thank you for your report. I am aware of this issue on some computers and I am looking at fixing it. :)

**Comment by seanfrisbey** [comment]
I would like to chime in to say that I am having this issue too, if it helps!

**Comment by Sebbe75** [comment]
Hi!
I have connected two external monitors to my laptop and every monitor (27 ") is devided i two subregions each. 
On my laptop the program shows wrong resolution 1280x720 ( see picture) but It should be 1920x1080.   On the closest external monitor #3 ( see picture) to the Laptop, subregion does not work when I want to attach a new window and I have to manually adjust it every time. 
![maxto-1](https://cloud.githubusercontent.com/assets/28047950/25430967/f1959722-2a7e-11e7-880d-935f59913878.jpg)
![maxto-2](https://cloud.githubusercontent.com/assets/28047950/25430976/f6d0801c-2a7e-11e7-81a3-a70163c0bcab.jpg)

**Comment by vegardlarsen** [comment]
@Sebbe75 Your issue is related to the mixed high-DPI and normal DPI monitors. See #30.

It is caused by Windows Forms, which is what MaxTo uses to display its own windows, does not support what is known as per-monitor DPI awareness. We are solving this in a future update by replacing Windows Forms altogether.

In your case, you have a 1.5 scaling factor, so the numbers displayed are accurate if you multiply them by 1.5. This only affects the resizing window, the regions will be stretched to cover the entire monitor.

It does not appear to be related to the issue experienced by @baabo.

**Comment by Sebbe75** [comment]
Looking forward for the update. 

Thank you !

**Comment by vegardlarsen** [comment]
Please see issue #30 for a possible resolution to this issue. :)
