### ISSUE TITLE
Center Window hotkey option?

### ISSUE THREAD

**Issue by Sawtaytoes** [digitalcreations/MaxTo#167]
Could you add a hotkey option to center a window on its display?

For instance, I could hit <kbd>Win</kbd> <kbd>Num5</kbd>, and it would center the window on the current display, either as-is or at 50% width.

**Comment by vegardlarsen** [comment]
That is an idea I haven't examined. There is nothing stopping us from doing this, so I may add this in the future.

**Comment by Lomacar** [comment]
I was thinking a similar thing, using Num5 as well. I would like Num5 to be a toggle to maximize and restore the window. Say you use the hotkeys to move a window to a region and it automatically fills that region. It would be nice if you could hit Num5 to "restore" a window to it's previous size, but if that size is too large then it should shrink just the height or width, as necessary in order to make it fit. I guess that means if the window was originally larger than the region in both dimensions then this button wouldn't do anything, the way I am describing it. But mainly I want such a feature for windows that should be small anyway, like the Calculator.

**Comment by geotay** [comment]
Num5 as in the numeric keypad? Some of us don't have one of those. Otherwise, I think this is a great idea.

**Comment by vegardlarsen** [comment]
I can confirm that this feature is coming, and has been implemented.

**Comment by vegardlarsen** [comment]
Check out issue #220, which supports this through the "recipes" feature. :)
