### ISSUE TITLE
Uninstall (and upgrade) fails if "Start with Windows" is checked but the scheduled task has been deleted

### ISSUE THREAD

**Issue by reidrankin** [digitalcreations/MaxTo#178]
Had to track down a failure while upgrading to the 2017-07 version, causing an "Installation ended prematurely because of an error" message. Turns out that uninstallation of the previous version fails when trying to remove the "Start with Windows" scheduled task if it doesn't exist.

I had moved the task to a different task scheduler folder, which caused my issue; this also resulted in the MaxTo options window still showed the "Start with Windows" box checked, but unchecking it would cause a crash.

**Comment by andriywu** [comment]
.net framwork 4.7 is needed but my pc with win10 is not supported by it.

**Comment by vegardlarsen** [comment]
@reidrankin I will have a look at if this can be done differently. It should not crash, but then again I wouldn't recommend moving the automatically created task either, as MaxTo may attempt to recreate it and you may end up with two tasks instead of one.

@andriywu Can you please elaborate on what you mean by this?

**Comment by vegardlarsen** [comment]
I am closing this issue, since this code is no longer part of the 2.0.0 preview releases of MaxTo, and therefore will not cause this issue going forward.
