### ISSUE TITLE
Regions are too small

### ISSUE THREAD

**Issue by Lomacar** [digitalcreations/MaxTo#189]
I am using a 43" 4K TV as a monitor. Frequently the regions are incorrectly scaled so that they only take up about a 10th of the space of the full monitor. They are squashed up in the top left corner. The rest of the monitor is regionless and as far as I can tell the regions don't actually work at all. In fact if I try maximizing a window, nothing happens, even if I move it inside the tiny regions. Sometimes restarting helps, I think. But the most effective way I have found to fix it is to adjust the Windows (text) scaling factor up and back down. (I have it set to 100%.)

**Comment by vegardlarsen** [comment]
Which version of Windows are you on? There have been a lot of changes to how Windows handles DPI in the latest releases, especially with Windows 10 and the different updates.

After changing the DPI in Windows, does MaxTo pick it up correctly if you restart it, or does this only happen when MaxTo starts with Windows?

Can you at any point see the DPI changing after starting Windows?

**Comment by Lomacar** [comment]
I am using the Anniversary edition. Where I am I don't have easy access to upgrade to the Creators Update, and besides I heard it has severe compatibility issues with some software that I use for work. Waiting to get the Fall Creators Update.

By DPI you mean the overall resolution of the monitor, like 1920x1080? I am running at 3840 x 2160 and haven't changed that, so I don't know what you are asking from me. I don't know any pattern for when it works and when it doesn't. Restarting MaxTo or the whole computer doesn't necessarily fix it.

I haven't noticed the resolution ever changing while I am using Windows.

**Comment by vegardlarsen** [comment]
DPI means Dots per inch, the setting in Windows it is known as "scaling". To make items on monitors with a higher DPI, Windows scales the monitors differently to make items appear to be the same size when you move it from e.g. a 4K monitor to a HD monitor. The problem is that Windows' scaling can sometimes mess up quite badly, and unless you are on the Creators Update, you should probably make sure Windows has the same scaling factor on all monitors.

Can you take a screenshot of the entire monitor where this problem occurs?

**Comment by vegardlarsen** [comment]
I am closing this due to lack of feedback.

**Comment by Lomacar** [comment]
The problem seems to have gone away on it's own anyway, probably after I updated Windows.
