### ISSUE TITLE
Windows switching hotkeys don't respect Win 10 virtual desktops

### ISSUE THREAD

**Issue by Lomacar** [digitalcreations/MaxTo#191]
If you have multiple desktops set up in Windows 10 and you try to cycle through Windows in a region, MaxTo will actually jump you around to different virtual desktops to find the next window. This is very undesirable behaviour. MaxTo should only bring up windows within the same region on the same desktop. As it is, this great hotkey feature is ruined for me.

Also, it seems that this feature only works on windows that are maximized within a region. Is this the intended behaviour? I think it should work on any window that is entirely within a region, or maybe even just mostly within a region (any given window would belong to whatever region most of it's pixels are in).

**Comment by vegardlarsen** [comment]
We are working on better virtual desktop support, so this will hopefully be fixed in a future release.

Cycling is intended to be used only for windows that are maximized to the region, correct. When I designed this,  there were basically 3 "kinds" of windows that could be included in this:

1. Windows that are maximized to the region
2. Windows that are completely contained within the region
3. Windows that partially overlap the region

After some experimentation, it felt most natural to only allow windows that were maximized to the region. A discussion may clearly be had if this was the correct choice, but it is clear to me that it is the least confusing one for users.

**Comment by Lomacar** [comment]
I look forward to the better virtual desktop support.

I don't think the current solution for switching windows in a region makes sense. I expect it to work like alt-tab (better, since you can go in two directions), but confined to a region. The only unclear thing for me is how to handle windows not fully inside a region. If I have a maximized window obscuring an unmaximized one, I still want to be able to switch to that smaller window. If there are differences of opinion on this matter then maybe you could make it an option in the settings.
