### ISSUE TITLE
Unable to override Win+Arrows for window movement

### ISSUE THREAD

**Issue by bojordan** [digitalcreations/MaxTo#198]
Unable to override Win+Arrows for window movement. Understanding this is default Windows behavior that is being overridden, it is intuitive to allow hijacking of the system keyboard shortcut to perform equivalent/enhanced behavior with MaxTo enabled.

**Comment by vegardlarsen** [comment]
This is something I have looked at, and have put off for now. We can successfully hi-jack those shortcuts, but there was a very nasty side-effect after doing so that we couldn't really get rid of (namely that the Start menu opens, because the Windows key appears to have been pressed by itself).

I know some other software has done this successfully, but I haven't been able to figure out how.
