### ISSUE TITLE
Highlight Regions hotkeys both highlight Alternate Region

### ISSUE THREAD

**Issue by jneuhaus20** [digitalcreations/MaxTo#216]
This is an issue for me because of a seemingly longstanding bug in Win 7 and beyond where reported monitor IDs don't always line up with those reported to the User (i.e. through Screen Resolution).  When I unplug my Surface from the dock and back in, my regions sometimes switch (typically my right Dell and the Surface), which I think is because the mapping changed, but not the user.config device paths (e.g. \\.\DISPLAYN).

In those instances, I'd like to quickly confirm my regions through highlighting before finding out the long way (change regions) or the hard way.  My main regions are coarser and therefore quicker to verify.

Highlight Main is set to Ctrl+Win+Num5, and user.config reports it as:
``` xml
<HotkeyAction>
    <Hotkey>NumPad5</Hotkey>
    <HotkeyModifierValue>10</HotkeyModifierValue>
    <UniqueId>HighlightRegionsMain</UniqueId>
</HotkeyAction>
```

Highlight Alternate is set to Alt+Ctrl+Win+Num5, and user.config reports it as:
``` xml
<HotkeyAction>
    <Hotkey>NumPad5</Hotkey>
    <HotkeyModifierValue>11</HotkeyModifierValue>
    <UniqueId>HighlightRegionsAlternate</UniqueId>
</HotkeyAction>
```

Win 10 Enterprise, MaxTo 2017.7.0.0, Surface Book 2, plus 2 Dell U3415W

**Comment by vegardlarsen** [comment]
Thank you for reporting this issue. We have fixed this in an internal build which we are hoping to release as an alpha release soon.

We have done a lot of work on identifying monitors by their name (e.g. Dell UltraSharp U2715H) instead of number in the user interface. 

In addition, we will allow you to choose how MaxTo identifies monitors:

- Using serial number, which makes sure we always will recognize a specific monitor. This will be the default.
- Using properties (such as resolution, DPI, video card port, etc.) which attempts to do the same thing (and is the fallback for monitors who do not expose their serial number)
- Using the monitor number (the device paths, `\\.\DISPLAY1`)

In addition, we are going to be dropping the main/alternate paradigm, and instead let you have an unlimited number of quickly loadable configurations.

I am closing this issue since I will not be doing anything more than this.
