### ISSUE TITLE
No icon in notification tray.

### ISSUE THREAD

**Issue by johnnya23** [digitalcreations/MaxTo#23]
I don't see how to do any configuring with out the notification icon, but its not there.

**Comment by vegardlarsen** [comment]
Closing this because of no response.

**Comment by Gappa** [comment]
I'm having the same problem right now - Windows 7 x64.

I can see all 3 MaxTo processes in the task manager, but no icon in the tray and when I try to "get it show" using the "Notification tray icons" (or however it is called in English version of Windows) config window it only says that MaxTo "is not currently active and will show in the tray the next time it will be active". So that's a dead end.

As expected, trying to run MaxTo again will tell me to look for in the they tray, where it isn't :)
However, If I kill the process(es) and run it again the icon does show up, but non of the system hooks will work :)

Currently I have MaxTo enabled to start with Windows, so thay may have an effect. Will try to disable and run it manually on the next restart.

**Comment by Gappa** [comment]
Update: well, that works, but the self -test is kinda finicky - it reports that the non-elevated 32-bit hook is not working, but x32 Firefox maximizes without any problems in all the defined areas.
