### ISSUE TITLE
Elevated Programs 

### ISSUE THREAD

**Issue by Rollyjoger85** [digitalcreations/MaxTo#237]
After having updated to Windows 1803 all my elevated programs no longer snap to the regions, they simply ignore the regions and go full screen all the time, running MaxTo with elevation fixes the issue, but i cannot run this service with elevated rights 24/7.

I'm running the latest 2017.07

**Comment by Rollyjoger85** [comment]
Somehow the issue has resolved itself, maybe from being run as admin once, everything is working as expected again.

**Comment by vegardlarsen** [comment]
Good. Sorry for late reply, I am currently on paternity leave.

The preview versions (see issue #220) should allow you to run MaxTo without elevation (but any elevated programs will not work with MaxTo).

When you run the current version MaxTo as admin once, it will set itself to start as admin on startup. When it does set itself to run on startup; we are able to bypass the UAC elevation prompt on consecutive startups because we are already elevated. That is probably what happened here.
