### ISSUE TITLE
2.0.0 Two is one 'status area' icon too many

### ISSUE THREAD

**Issue by DavidGretzschel** [digitalcreations/MaxTo#245]
There should only be one icon in the selection screen, here. Also only one of them even shows up.

![image](https://user-images.githubusercontent.com/23729465/42761425-c5f93bca-890d-11e8-85ec-4e2728df0317.png)

**Comment by vegardlarsen** [comment]
I am not sure why this is happening, but I will investigate.

**Comment by vegardlarsen** [comment]
Turns out this is an artifact of our installer software, which we cannot easily change. We are looking at other methods for installation in the future, as we have had multiple issues with this software. I am therefore closing this, as we won't be making any fixes here until we can replace the entire installer.
