### ISSUE TITLE
Chrome says that MaxTo must be removed

### ISSUE THREAD

**Issue by GrishaevPavel** [digitalcreations/MaxTo#253]
![2018-09-19_1026](https://user-images.githubusercontent.com/31139532/45737545-c4a07880-bbf6-11e8-9448-303cd711909d.png)

**Comment by vegardlarsen** [comment]
This appears to be the same issue as #251. Do you have a virus on your computer, as was the case there?

**Comment by GrishaevPavel** [comment]
I can't be sure about a virus, I use kaspersky antivirus and it found nothing.

**Comment by vegardlarsen** [comment]
Which version of MaxTo are you running? Are you on the 2.0.0-alpha.5 preview release (details in issue #220)?

**Comment by JoeOrtiz** [comment]
This happens with myself as well, but usually after a full system crash, which has happened like 4 times in the past few months.

I finally went in to investigate, even though sometimes I get the BSOD, I see these right before the crash:

`
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name=".NET Runtime" /> 
  <EventID Qualifiers="0">1026</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-09-19T14:43:35.460987400Z" /> 
  <EventRecordID>12957</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-P30ODBJ</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>Application: MaxTo.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: exception code c0000005, exception address 000000003D091888 Stack: at System.Windows.Forms.UnsafeNativeMethods.PeekMessage(MSG ByRef, System.Runtime.InteropServices.HandleRef, Int32, Int32, Int32) at System.Windows.Forms.UnsafeNativeMethods.PeekMessage(MSG ByRef, System.Runtime.InteropServices.HandleRef, Int32, Int32, Int32) at System.Windows.Forms.Application+ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr, Int32, Int32) at System.Windows.Forms.Application+ThreadContext.RunMessageLoopInner(Int32, System.Windows.Forms.ApplicationContext) at System.Windows.Forms.Application+ThreadContext.RunMessageLoop(Int32, System.Windows.Forms.ApplicationContext) at MaxTo.Program.Main(System.String[])</Data> 
  </EventData>
  </Event>
`

`- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-09-19T14:43:35.910987800Z" /> 
  <EventRecordID>12958</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-P30ODBJ</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>MaxTo.exe</Data> 
  <Data>2017.7.0.0</Data> 
  <Data>595617db</Data> 
  <Data>MaxTo.Hook64.dll_unloaded</Data> 
  <Data>0.0.0.0</Data> 
  <Data>595617d3</Data> 
  <Data>c0000005</Data> 
  <Data>0000000000001888</Data> 
  <Data>1f8c</Data> 
  <Data>01d4502652d803e1</Data> 
  <Data>C:\Program Files\MaxTo\MaxTo.exe</Data> 
  <Data>MaxTo.Hook64.dll</Data> 
  <Data>d2947406-19d8-4530-8cfd-6af8c3ea5a5a</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>`

`- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2018-09-19T14:43:38.795253400Z" /> 
  <EventRecordID>12960</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DESKTOP-P30ODBJ</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>MaxTo.exe</Data> 
  <Data>2017.7.0.0</Data> 
  <Data>595617db</Data> 
  <Data>MaxTo.Hook64.dll_unloaded</Data> 
  <Data>0.0.0.0</Data> 
  <Data>595617d3</Data> 
  <Data>c000041d</Data> 
  <Data>0000000000001888</Data> 
  <Data>1f8c</Data> 
  <Data>01d4502652d803e1</Data> 
  <Data>C:\Program Files\MaxTo\MaxTo.exe</Data> 
  <Data>MaxTo.Hook64.dll</Data> 
  <Data>9003f14d-615c-493f-ac90-fbda25f1cc8e</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>`

**Comment by GrishaevPavel** [comment]
I have strange Windows freezes after april 2018, after which I have to reset, but I don't know the reason, all seems to be good and event log has no info about reasons, and I don't say that the problem is in MaxTo, who knows )

**Comment by vegardlarsen** [comment]
This Google Chrome issue has now started appearing on my machine as well, so there should be some way to reproduce and fix it. I will investigate how this detection is done by Chrome, and see if this is something we can fix.

**Comment by vegardlarsen** [comment]
This issue appears to have been reversed by updated Chrome versions.
