### ISSUE TITLE
[2.0.0-alpha5] Active/Passive mode settings

### ISSUE THREAD

**Issue by eg009** [digitalcreations/MaxTo#256]
Active mode automatically assumes a number of features enabled(and vice versa for passive) w/o any explicit way to change their behavior.
+ Window transparency
+ Drag-n-drop maximizing to region (shift modifier)
+ Fixed [Shift] button for ^

I used 2017 version passive-always with opaque windows and shift+ drag&drop to work with regions. Right now both features are broken for me. 
I'm either forced to use passive, w/o being able to use [shift] to place windows in regions, but with window opacity
Or have window transparecy + intrusive behavior on standart maximize action. Plus no way to change the modifier key.

//shift+drag animations are also a bit confusing with no way to tweak them

**Comment by vegardlarsen** [comment]
Active/passive works differently in 2.0 than in previous versions, that is correct. Instead of changing what MaxTo does, passive mode is now actually deactivating the parts of MaxTo that require global hooks to be set. This means that when MaxTo is not active, it should no longer be loaded into other processes. Note that you should still be able to use keyboard shortcuts/recipes.

This is very much by design, as this enables you to use any software that may be incompatible with MaxTo, while MaxTo is still running. 

We may at some later stage re-introduce some other mechanism for controlling this at a finer level, but it will not happen before 2.0 releases.

How do you find the shift+drag animations confusing?

**Comment by eg009** [comment]
Ok, thx for the heads-up! Will revert to 2017 then

Shift+drag animations are slow, so the visual feedback is delayed for some time and it makes it not that useful.
