### ISSUE TITLE
Everything is slow, really slow and a resource hog.

### ISSUE THREAD

**Issue by Transisto** [digitalcreations/MaxTo#27]
Moving windows is slow, even right clicking the tray icon take as much as 2 seconds to show options.

http://i.imgur.com/FvIHmGp.png

(on an i7 4ghz)

**Comment by Transisto** [comment]
http://i.imgur.com/7heNvCR.png

Different kind of bug, randomly decide to go 100% CPU haven't used any of it's feature yet.

Uninstalling.

**Comment by timkay** [comment]
I have the same problem. It takes seconds for the dialog to show up when I right-click on the tray icon.

Also, after I resume from sleep, it takes maybe 30 seconds before the hotkeys work. And they get queued up, so windows skitter around until it catches up.

This product has always been sluggish this way, even under Windows 7, and across multiple computers. I just assumed it was poorly written. I stay with it because its benefits (slightly) outweigh this annoying behavior.

The self test shows 4 green checkmarks. It says it can't test the hot keys because of security settings.

**Comment by vegardlarsen** [comment]
@timkay This is definitely not how it is supposed to behave. I have been looking at this, but the trouble is that on all the machines I have access to it behaves properly. Even across virtual machines (which are slow to begin with) I haven't experienced it.

Do you have any other software (e.g. antivirus) that may be interacting with MaxTo in some way?

**Comment by Transisto** [comment]
I'm not using the software anymore but it could be because I was using a 4k
screen.

**Comment by timkay** [comment]
I am running on a 4K display connected via a DisplayLink USB-to-DisplayPort
adapter. I get excellent performance except for MaxTo. (I can watch
Netflix, although not well at full screen.)

Once it's "warmed up", MaxTo works fine. Just that it takes a long, long
time to get going after a reboot.

On Thu, Jan 7, 2016 at 10:22 PM, Vegard Andreas Larsen <
notifications@github.com> wrote:

> @timkay <https://github.com/timkay> This is definitely not how it is
> supposed to behave. I have been looking at this, but the trouble is that on
> all the machines I have access to it behaves properly. Even across virtual
> machines (which are slow to begin with) I haven't experienced it.
>
> Do you have any other software (e.g. antivirus) that may be interacting
> with MaxTo in some way?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/digitalcreations/MaxTo/issues/27#issuecomment-169908839>
> .
>



-- 
Tim Kay
m: +1-650-248-0123
Skype: timkay
