### ISSUE TITLE
Hotkey to set Passive Mode

### ISSUE THREAD

**Issue by themattkenney** [digitalcreations/MaxTo#270]
In the new Beta version you can set recipes, but I found no way to set a hotkey to turn MaxTo from active to passive. This feature saves a lot of time when you undock your laptop.

**Comment by vegardlarsen** [comment]
This is absolutely something I want to do. I am putting this on the backlog to happen after 2.0 goes final (so it will probably be in 2.1).

**Comment by jdunham22** [comment]
Another vote here for passive mode, which was all I ever used in the old version. I think it's a much better and more natural experience to have normal Windows behavior and then when you press an extra key (like Shift) then an extra behavior happens. 

Imagine if someone is using my computer briefly then nothing is behaving the normal way and they get confused.  It's much easier to train myself to do an extra key than to train everyone else to work around my non-standard configuration.  

Even for myself I still find it jarring when I maximize a window and it doesn't fill the screen like I expect.  If I were doing that extra action (holding down shift) then I would be expecting something special but most of the time I am focused on something totally different (like my actual job) and the weird maximizing behavior is distracting.

**Comment by colthreepv** [comment]
Sorry, but I don't see this on 2.1.0-alpha2

Is that such an hard feature? cmon every developer has settings flags, just add one! 🎏

**Comment by vegardlarsen** [comment]
@colthreepv Currently we don't have passive mode, so we would need to bring this back as well. It is a bigger deal than you may think from the description.

**Comment by vegardlarsen** [comment]
I have re-implemented "Passive mode" for 2.1.0-beta.2. Since 2.0 you can disable all of MaxTo, which is not the same thing as Passive mode. Disabling MaxTo would prevent MaxTo from loading into other processes, Passive mode does not do this. I don't think there will be a shortcut key for disabling in the immediate future.

Passive mode will only affect window maximize events (i.e. requiring you to press Shift to maximize to a region). My thinking is that in version 3.0, Passive mode will also apply to the drag to region functionality. That is however a breaking change, which is why I am holding that change back.

However, as it stands right now, we do not have the possibility to toggle passive mode from a recipe or a hotkey, and I think I want to do that in a more general way (that would also let us toggle other settings).

**Comment by vegardlarsen** [comment]
I have just added a command to change settings from the command line. Settings changes take immediate effect, so you can toggle e.g. passive mode from the command line:

```
maxto settings set /Setting behavior.passiveMode /Mode On
maxto settings set /Setting behavior.passiveMode /Mode Off
maxto settings set /Setting behavior.passiveMode /Mode Toggle
```

This command will be in 2.1.0-beta.2.

**Comment by thewavelength** [comment]
This is buggy. It is not working reliably when passive mode is activated and even after disabling passive move, some windows still need to have shift pressed to let it work (the application in question was even started _after_ disabling passive mode). No log file entries.
