### ISSUE TITLE
Crash when changing keyboard shortcuts

### ISSUE THREAD

**Issue by tomstachura** [digitalcreations/MaxTo#278]
While changing regions or redefining shortcuts the app crashes. I just installed it 10 minutes ago and had it crash 5 times already. It's almost unusable. Every time you make a settings change, you need to restart. I am running it on W10 with a 4k monitor.

**Comment by vegardlarsen** [comment]
Thank you for reporting this. Can you get me the log file (`%AppData%\MaxTo\maxto.log`) so I can figure out what is going on?

**Comment by tomstachura** [comment]
Hi – here you go. I included the config as well.

 

BTW – it would’ve been nice if the settings were imported from the previous version 😊.

 

Great product!!

 

Tom

 

________________________________________
Tom Stachura | 1-604-525-7096 | tom@stachura.me <mailto:tom@stachura.me> 
  <https://twitter.com/tomstachura>   <https://www.linkedin.com/in/tomstachura>

**Comment by vegardlarsen** [comment]
@tomstachura Unfortunately you can't send attachments via e-mail to Github. You'll have to go on the site and upload them here, or they disappear on the way :)

**Comment by tomstachura** [comment]
Funny - github doesn't recognize .json files.
[config.json.txt](https://github.com/digitalcreations/MaxTo/files/2589676/config.json.txt)
[maxto.log](https://github.com/digitalcreations/MaxTo/files/2589677/maxto.log)

**Comment by vegardlarsen** [comment]
@tomstachura Thanks for those files. The crash is because MaxTo tries to register a keyboard shortcut that is already taken by another program. Specifically the shortcut key is: Control+Windows+NumPad4.

This error is no longer be fatal in the 2.0.0-beta.3, which was released on Friday. So if you upgrade, the issue should no longer lead to a crash.

**Comment by tomstachura** [comment]
Not sure why this is closed - assigning keyboard shortcuts still crashes MaxTo into shreds.

**Comment by tomstachura** [comment]
[maxto.log](https://github.com/digitalcreations/MaxTo/files/2599989/maxto.log)

**Comment by vegardlarsen** [comment]
Does this happen on startup or when you try changing a shortcut?

**Comment by tomstachura** [comment]
Changing ahortcut

**Comment by vegardlarsen** [comment]
I will be looking into this issue.

**Comment by juggzie** [comment]
@vegardlarsen same issue here. wanted to try maxto instead of winsplitrevolution, but it crashes every time. now i cannot even start it. was not able to re-arrange even a single window. 
After changing setting in keyboard shortcuts issue doesn't go away and i cannot access UI to even reset it back. Tried editing config (whatever i found in installation folder) from .NET 4.6.1 to 4.7.2 which is what i have, but it doesn't do anything.
Gonna reinstall it now. Here's logs, just in case

[maxto.log](https://github.com/digitalcreations/MaxTo/files/2624760/maxto.log)

**Comment by juggzie** [comment]
Both beta and even reinstalled stable cannot be even tested withing the 30 day period, just because it crashes without even be able to launch.
Is there anything that I can troubleshooting to make it work?
If I cannot test it, i cannot switch to maxto and stay with it.

**Comment by vegardlarsen** [comment]
@juggzie You can always [go back to the stable release](https://maxto.net/release). Your issue does not seem to be related to this issue. Your log is inconclusive, but I think there are two things you could do.

1. Delete the "MaxTo" scheduled task in Task Scheduler.
2. Edit your configuration file (`%AppData%\MaxTo\config.json`) and `startup.startOnLogon` to `false` (for now).

**Comment by vegardlarsen** [comment]
I have just fixed this issue; it was a cross-thread issue (trying to unregister a hotkey from a different thread than it was registered on).

The fix for this will be in 2.0.0-beta.4.
