### ISSUE TITLE
Maxto setup

### ISSUE THREAD

**Issue by skreda** [digitalcreations/MaxTo#29]
I download Maxto to my download folder (1.45MB). I have windows Vista. When I run the exe file, I get a brief response and then nothing happens. I've tried this with several different Maxto downloads.

**Comment by vegardlarsen** [comment]
@skreda Did you try any of the two things I suggested to check for above?

**Comment by skreda** [comment]
the computer in question is at my office. I will try it on Friday and get back with you then. Thanks. 
----- Original Message -----

**Comment by skreda** [comment]
I've attached the screen shot. I was able to follow the certificates and all status is OK. What now? 
----- Original Message -----

**Comment by vegardlarsen** [comment]
@skreda I'm afraid attachments don't work on Github when you reply by e-mail.

**Comment by skreda** [comment]
I just sent the screenshots showing that all the certificates were marked OK 
----- Original Message -----

**Comment by skreda** [comment]
On the digital signatures: key issues and basic constraints is marked with a yellow question mark. I tried the download on a second vista machine and get the same result. An almost instant stop. 
----- Original Message -----

**Comment by skreda** [comment]
Could the problem be antivirus software? Vista? The download? other settings? 

----- Original Message -----

**Comment by vegardlarsen** [comment]
@skreda I still do not have the screenshots. If you log in to Github you can upload your screenshot by dragging and dropping images into the text editor here. It does not work if you reply by e-mail.

**Comment by simplyeffectiveweb** [comment]
Sometimes threads like this seem to get diverted by semantics.

Im on Vista SP1 (yes, I know), and Maxto installation is not working. As follows:

 - Downloaded from Maxto site (Maxtoseetup-2015-02.exe)
 - Running program results in nothing (as in nothing happens, no dialgue boxes, no errors shown)

This is without question a Maxto installation issue. I use a variety of software and test others. So software gets installed with reasonable frequency. (and system admin is done to virus check, windows updates, etc).

I'm not going to go further with debugging this because these situations normally result in a circle of obvious Windows questions and trying stuff that go nowhere. I'm happy my system works and won't change it for this program (no offence intended, just the way Windows makes people think). However, If a solution or update becomes available, I'll happily try again,

**Comment by vegardlarsen** [comment]
@skreda I am assuming you are running Windows Vista SP1? You should update to SP2, and MaxTo should work fine.
