### ISSUE TITLE
Reenter License Key After Each Restart

### ISSUE THREAD

**Issue by steinal75** [digitalcreations/MaxTo#314]
After each restart of the computer I have to reenter the license key once again. MaxTo starts up the same way as it started up after the installation. After the reenter of the license key it shows the regions assigned in the last session which is fine but the necessity of reentering the license key each time is annoying

**Comment by vegardlarsen** [comment]
Which version of MaxTo are you running? Is your machine domain managed, e.g. is there something that cleans out registry keys or local directories running on boot?

**Comment by PMTSGIN** [comment]
Hi,
I have the same problem with the 2.0.0-rc2 version. 
Before, with the 2.0 beta version, eveything was ok!
Do you have any recommandation ?
Thanks.

**Comment by vegardlarsen** [comment]
@PMTSGIN Do you get a file called `%AppData%\MaxTo\license.txt` that contains your license key? (Do not copy and paste it here)

Is that file still there after a reboot?

**Comment by PMTSGIN** [comment]
No, this file doesn’t exist.

After I put my license key, I can see my license detail in the settings (see screenshot), but no license.txt file in the %AppData%\MaxTo\ folder !

**Comment by crisitunity** [comment]
This is still happening in v2.0.1 - even after just restarting the app without rebooting the PC.
Machine is domain joined, no clearing of reg keys or files to my knowledge (can check specifics for you if you have a list).
I noticed that I don't seem to get a license.txt file even while the app is running. Reports as licensed in the GUI though.

**Comment by vegardlarsen** [comment]
@PMTSGIN @crisitunity What if you manually create the license file? It should only contain the license code that you would otherwise paste into the program. Save it to `%AppData%\MaxTo\license.txt`.

**Comment by crisitunity** [comment]
I will give this a try but don't have access to that PC until 7th May. Will post back here though once tested.

**Comment by crisitunity** [comment]
@vegardlarsen Creating the file manually works.

**Comment by bluevulpine** [comment]
Also seeing this on a domain joined work PC. Windows 10 (1903), MaxTo 2.0.1. The license.txt file is not created in %AppData%\MaxTo\ although there are a number of other files there - multiple maxto log files, a monitor folder, and a config.json.

The logs contain a number of exceptions around web requests due to not properly accessing the current system proxy settings - specifically, proxy **credentials** are being missed:

`System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.
`

Additionally, it appears to be attempting to create a startup task without getting proper permission first:

`2019-08-23 09:27:03 [Core@2.0.1.499] [Information] Found startup task with incorrect definition. Recreating task.
2019-08-23 09:27:03 [Core@2.0.1.499] [Error] Could not register startup task during startup.
System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Microsoft.Win32.TaskScheduler.V2Interop.ITaskFolder.DeleteTask(String Name, Int32 flags)
   at Microsoft.Win32.TaskScheduler.TaskFolder.DeleteTask(String name, Boolean exceptionOnNotExists)
   at MaxTo.Core.Update.InstallHelper.DeleteScheduledTask()
   at MaxTo.Core.Settings.LoginRegistrationService.Register()
   at MaxTo.Core.Settings.LoginRegistrationService.InitializeAsync()
`

I don't see any messaging at all related to writing the license file. There doesn't appear to be any sensitive data in the log so I'm attaching it for reference. 

[maxto20190823.log](https://github.com/digitalcreations/MaxTo/files/3534977/maxto20190823.log)
