### ISSUE TITLE
MaxTo loose track on displays when one monitor is unplugged and plug again.

### ISSUE THREAD

**Issue by asRIA** [digitalcreations/MaxTo#32]
Windows 8.1 x64

Steps to reproduce:
- plug all monitors
- configure max to to work with 2 monitors (snapping areas)
- [everything works fine]
- unplug secondary monitor and plug in again
- max to cannot determine region snapping and a window is moving to some invisible place. Frequently size of the window is set to minimal value

Steps to fix:
- reset restart maxto. Origin configuration is well set.

Please let me know how can I provide additional information to fix this problem.

// I'm working on a laptop, thus is not uncommon to unplug monitors.

**Comment by vegardlarsen** [comment]
You are right, this is a bug. There is most likely something wrong with how MaxTo handles the message when the screen configuration changes. I will have a look and see what I can figure out.

**Comment by vegardlarsen** [comment]
I finally figured out what was happening here. 

We subscribe to two events that happens when the working area changes: `WM_SETTINGSCHANGED` and `SystemEvents.DisplaySettingsChanged`. Whenever a monitor is attached or detached, we typically first receive a few `WM_SETTINGSCHANGED` messages and then a single `SystemEvents.DisplaySettingsChanged`. 

When any of these happen, we check `Screen.AllScreens` and use the `WorkingArea` property of each screen to determine the working area (the portion not covered by the taskbar). MaxTo uses this value to determine where the regions go.

The problem is that for at least 100 milliseconds after these messages are received, Windows reports the wrong working areas. By then, MaxTo had already set up the working areas.

The solution became to delay MaxTo's reaction to these events by a full second, and then apply the changes, now with the correct working areas. Not ideal, but it works. Will ship in next release.

cc: @asRIA
