### ISSUE TITLE
No Numeric Keypad and No NUMLOCK

### ISSUE THREAD

**Issue by wbochar** [digitalcreations/MaxTo#340]
No Numeric Keypad or NUMLOCK. There are a lot of keyboards out these days without the Keybpad.
A lot of the Recipes do not work with the regular arrow key (as opposed to the numpad arrows)

 - Windows version:10
 - MaxTo version 2.0.0 beta10

**Comment by vegardlarsen** [comment]
@wbochar Thank you for reporting this. The problem is that Windows has started claiming more and more global keyboard shortcuts, so we haven't been able to find enough shortcut combinations for MaxTo to use as default for computers without a numeric keypad.

If you have any suggestions for the default recipes I would be happy to hear them. :)
