### ISSUE TITLE
auto-create region from opened windows

### ISSUE THREAD

**Issue by miked-mellanox** [digitalcreations/MaxTo#353]
use-case:
* user open windows and lays them out on the screen
* maxto reads windows positions and generate regions automatically

**Comment by vegardlarsen** [comment]
Thank you for your suggestion. While I can see the potential use case here, there are several pitfalls:

- What about open spaces (without windows)? Do they become their own region?
- What happens to partially overlapped windows? Do we create a region of the part of the window that is visible?

I think this would get confusing for the end user quite quickly, not minding how they would set up their windows to be pixel-perfect to begin with?

**Comment by miked-mellanox** [comment]
it can be defined as limitations and no need to support overlapping and open spaces. 
The only interesting and *easy* case when user positioned windows, forming exact/perfect match and wants to clone it into "regions".

**Comment by vegardlarsen** [comment]
The problem is that solution doesn't work with how regions work internally in MaxTo. We cannot have empty spaces with how it is set up today.

At the same time, getting this to work for the end user would be very fiddly. I'm sorry to say I can't see that this suggestion has any chance of actually being turned into a usable feature.
