### ISSUE TITLE
Active Mode Only When Using External Monitor

### ISSUE THREAD

**Issue by poita66** [digitalcreations/MaxTo#356]
**Is your feature request related to a problem? Please describe.**
Every time I use my laptop without an external monitor, I need to switch MaxTo to passive mode, which I invariably forget to do and end up maximizing into regions that are too small for my laptop monitor.

**Describe the solution you'd like**
A setting to enable active mode only on external monitors

**Describe alternatives you've considered**
A setting to specify which monitor to apply the regions to. That way I could specify no regions on my laptop monitor. This would also allow me to use different regions on different sized monitors.

**Additional context**
I'm using the stable version of MaxTo, so there might be a solution in the beta

**Comment by vegardlarsen** [comment]
There is not a solution in the current betas, and it won't make it into 2.0 final either. 2.0 does not even have the same active/passive mode setting as 2017.07 does (it defaults to always be passive), but because of feedback this is something that we definitely will be bringing back in a point release.

When it comes to your suggestion, reversing the mode across monitors comes at a cost of intuitiveness. That would mean that dragging a window from a passive to an active monitor while holding Shift would go from showing previews on the first monitor to not showing them on the second.

By the way you are writing here I am assuming you only keep either the external or the internal monitor active on your machine? 2.0 does something different with monitors, instead of storing your regions based on the monitor number, it tries to use the serial number of the monitor. This means that you can have a specific set of regions for your external monitor, and a different set of regions for your internal monitor. That could help you in your case?

**Comment by poita66** [comment]
I just wanted to let you know that the issue I was having is solved by 2.0, by allowing me to setup regions for monitors based on their ID (I simply don't setup regions on the laptop screen).

Also, I'm absolutely loving MaxTo 2.0!

**Comment by vegardlarsen** [comment]
@poita66 Thank you for your update. Great to hear :)
