### ISSUE TITLE
Open multiple instances of the same application

### ISSUE THREAD

**Issue by heystenner** [digitalcreations/MaxTo#359]
**Is your feature request related to a problem? Please describe.**
When I try to launch certain applications through a recipe, some of them (for example, the Trello desktop app) don't open up in a seperate window, but just highlight an already open window. But if I wanted, for example, set up a new work environment on another virtual desktop/monitor in a certain layout, I can't do that due to this restriction. Some apps will appear as expected, others won't.

**Describe the solution you'd like**
It would be great, if I could run a recipe that opens all specified applications at the location I want, giving me my complete workstation setup in an instance - independent of the circumstance of one of them already running on another monitor/virtual desktop.

**Describe alternatives you've considered**
Until now, I can only manually open a new instance for the program, using SHIFT+clicking the application or right-clicking on the taskbar and running it and then moving the app window to its location. - At least those are the ways I have tried so far, but none of them is what I'm looking for regarding MaxTo.

**Comment by vegardlarsen** [comment]
Hi, and thank you for your suggestion. There are ways overriding the one-instance policy of applications could be done (using virtual machines to run separate instances of Windows come to mind); but they are far outside the scope of what MaxTo is supposed to do. The reason is that these programs all use different mechanisms for ensuring they are the only instance on your desktop. 

Some of these methods include: 
- `GlobalAddAtom`
- checking if processes with the same name are running
- `EventWaitHandle`
- lock files
- memory mapped files
- [other IPC mechanisms](https://docs.microsoft.com/en-us/windows/desktop/ipc/interprocess-communications)

This makes it very difficult to do this at all; since overriding all of these implementations for different programs seems impossible.

Which is the next point; what would happen if you were to successfully override a program's one-instance policy? There is no way to know ahead of time. MaxTo's second instance would crash (maybe the first one would as well, I am not sure).

I think you would be better served by poking e.g. Trello and asking why they have a one-instance policy, and asking if it can be reversed?

**Comment by heystenner** [comment]
@vegardlarsen thank you, that gives me an impression of the difficulties and it's understandable MaxTo can't handle that. I'll try writing a script that does the necessary stuff and reach out to the app publishers.
