### ISSUE TITLE
do not save regions setting

### ISSUE THREAD

**Issue by hangmana** [digitalcreations/MaxTo#362]
**Describe the bug**
At first: After Windows 10 restart, MaxTo(2.0.0-rc.2) do not restore regions on screen.
2: MaxTo(2.0.0-rc.2) crashing when we try to save presets

**To Reproduce 1**
1. Setup regions
2. click to use regions
3. restart Windows10
4. See error =  Regions cleared

**To Reproduce 2**
1. Setup regions
2. click to save
3. wait for a second
4. See error =  MaxTo crashed

**System information:**
 - Windows version: 10.0.17134.590
 - MaxTo version: 2.0.0-rc.2

**Additional context**
[SquirrelSetup.log](https://github.com/digitalcreations/MaxTo/files/2957548/SquirrelSetup.log)
[maxto20190312.log](https://github.com/digitalcreations/MaxTo/files/2957550/maxto20190312.log)

**Comment by vegardlarsen** [comment]
Hi,

number 2 has been handled in issue #360 and will be fixed in the next release.

How many monitors do you have? Did you re-arrange them?

From the logs it appears that you have created a few copies of some configuration files, including the monitor configuration files? I am assuming "копия" means "copy" as Google Translate tells me. You may have success by changing the [Monitor identification setting](https://maxto.net/documentation/configuration/monitor) to identify by device names instead. 

It appears that your monitor's properties has changed between reboots, which could be why MaxTo thinks it is a new monitor.

**Comment by hangmana** [comment]
i have notebook + one monitor... And i tried to identifie monitors with different options (numbers\propeties\SN), it did not help me..

About "config - copy", i saved the original config file to create different config. i tried to create a new config manually and it did not work too.
but it helped me to save presets...

Every restart Windows10 i see cleared screen without any settings.

**Comment by hangmana** [comment]
Today i tried to change language in MaxTo and the program told me "The lang will change when MaxTo is restarted." and i clicked button "Restart now".
After restart i saw cleared regions. so sad. ((

**Comment by vegardlarsen** [comment]
Can you try exiting MaxTo, deleting the contents of `%AppData%\MaxTo` completely, and then starting MaxTo and setting up some regions? Then ZIP up the folder and send it to me?

That should give me a limited set of logs to look through, and hopefully help narrow it down.

**Comment by hangmana** [comment]
Done.

**Comment by vegardlarsen** [comment]
@hangmana Sorry I wasn't clear. You cannot send ZIP files to Github. You'll have to use the support e-mail; support AT maxto DOT net.

**Comment by vegardlarsen** [comment]
Closing this issue as I think it has been solved in version 2.1.0 (in preview), and we did not get any further feedback from the customer.
