### ISSUE TITLE
rc2 no additional presets

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#363]
release says: 4 new presets
However I can only see 2 presets.
![image](https://user-images.githubusercontent.com/23729465/54430600-5e6b5d00-4724-11e9-9ab4-c14e239b6d9b.png)

**Comment by vegardlarsen** [comment]
@davidermined Because of the way our configuration system works, the presets are only "created" when starting without a configuration. So this is expected behavior. We will probably at some point add a "Reset to default settings" option. You can reset the settings to default now by deleting `%AppData%\MaxTo\config.json`.

However, due to a localization bug, all of the new presets will lack names in rc.2. :(
