### ISSUE TITLE
MaxTo doesn't remember layouts for virtual Desktops

### ISSUE THREAD

**Issue by davidermined** [digitalcreations/MaxTo#368]
It's not a grid or cube or anything fancy, the Windows Workspaces are just a simple ordered list.
Problem:
So I might have workspace 2 with one specific layout.
I would want to be able to delete the workspace, because it's unneeded, then recreate it and then have my old layout there.
I don't want to screw around with Presets, especially since they're all per screen.
I have four screens.
Assuming that I have up to four workspaces, that I delete regularly for "cleaning up after work": After setting up my workplaces to get into workmode, I'd have to do 12 actions. That ain't good.

possible complicating factor (maybe this already works like I want it to, after all):
I use 
https://github.com/sdias/win-10-virtual-desktop-enhancer
to make Windows Workspaces actually useful.

**Comment by vegardlarsen** [comment]
The problem here is that Windows' virtual desktops aren't really "just a simple ordered list". It is an unordered list (I have gotten this confirmed from the Windows team at Microsoft when we tried to get them to support a better API to program against). There are lots of subtleties involved here.

Therefore, MaxTo stores the regions based on virtual desktop identifier, which is a randomly generated identifier (by Windows, not us), to remember which settings to apply to a virtual desktop. 

So while it may appear to you and I as end users that the virtual desktops are simply numbered from left to right, this isn't actually the case.

**Comment by davidermined** [comment]
well.... that's very sad. A solution would be, if one could have presets
for whole virtual desktops, which include several monitors.
(meaning, that the preset says: preset A for monitor 1, preset B for
monitor 2)
Or even a preset that's available, if the number of "virtual desktops" is
available, that sets up each "virtual desktop" and each monitor
with the appropriate regions.
Any chance, that's happening?
(otherwise, I'll just have to learn never to close out my virtual
desktops..... which feels a bit unclean.)

Am Fr., 15. März 2019 um 15:59 Uhr schrieb Vegard Andreas Larsen <
notifications@github.com>:

**Comment by vegardlarsen** [comment]
The problem about using "numbered" virtual desktops, is that once you delete a virtual desktop, the layouts on all the other desktops will "shift".

Say you start out with 3 desktops, then delete the first. The regions on the remaining two virtual desktops would now be out of alignment with the windows on them, because they would now be numbered differently.
