### ISSUE TITLE
AnyStatus support for MaxTo

### ISSUE THREAD

**Issue by AlonAm** [digitalcreations/MaxTo#381]
Hi There,
My name is Alon Amsalem, I am the author of [AnyStatus](https://www.anystat.us).
One of the users reported that AnyStatus does not work well with MaxTo because it implements a custom UI. Could you please advice on how to improve that integration? Is there some article that I can read to learn more?
Thank you!

**Comment by vegardlarsen** [comment]
Thank you for your request. I think this is something we can probably work into our documentation is some manner, so I'll take a stab at answering this as exhaustively as I can before delving into the details of AnyStatus.

MaxTo basically has a few qualifiers for windows. I'll try to split this into feature areas.

Important to note: For any event MaxTo intercepts, it will make a call to get the window handle of the root window: using `GetAncestor(hwnd, GA_ROOT)` and treat that as the window being worked on.

### Maximize, minimize events

MaxTo relies on a [CBT hook](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644977%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) to catch important events regarding windows. This allows it to monitor which window is active, and to see when a window is maximized or minimized (`HCBT_MINMAX`).

It then will manipulate the window. Depending on the circumstances, these method calls are involved:

- `MoveWindow` (only if a specific [compatibility shim](https://maxto.net/shims) is set for your app).
- `PostMessage` (`WM_ENTERSIZEMOVE`, `WM_EXITSIZEMOVE`)
- `SetPosition` with `SWP_NOZORDER | SWP_NOSENDCHANGING`. Can happen twice in quick succession.
- `SetProperty` and `RemoveProperty` to remember details about a window in MaxTo-internal properties.

### Window subclassing

Some features are based on window subclassing, because it requires closer interaction with (e.g. snapping window edges to other windows, window transparency), and it basically runs this check to see if the window is eligible for being subclassed:

```cpp
if (!(windowStyle & WS_CHILD) && (windowStyle & WS_VISIBLE) && !(windowStyle & WS_POPUP)) {
    SetWindowSubclass(hwndRootWindow, SubclassFunc, SUBCLASS_ID, 0);
}
```

It does this in response to a CBT hook on any of these events: `HCBT_CREATEWND`, `HCBT_MOVESIZE`, `HCBT_SETFOCUS` and `HCBT_ACTIVATE`. I don't think you can "opt out" of creating these events, this is something Windows does automatically.

MaxTo uses subclass ID `79832`. It is important that your application does not use the same subclass ID.

**Comment by vegardlarsen** [comment]
@AlonAm Specifically for AnyStatus Desktop, it appears to react "wrongly" to MaxTo trying to manipulate its position. As I outlined above, this is usually:

1. `PostMessage(hwnd, WM_ENTERSIZEMOVE)`
2. `SetWindowPos(hwnd, SWP_NOZORDER | SWP_NOSENDCHANGING)` (can happen twice if on a system with multiple different DPIs)
3. `PostMessage(hwnd, WM_EXITSIZEMOVE)`

It appears AnyStatus will move correctly, but does not pick up on the sizing?

**Comment by AlonAm** [comment]
Thank you for the detailed response. I will look into it soon.

**Comment by vegardlarsen** [comment]
Closed as AnyStatus has resolved this on their end.
