### ISSUE TITLE
Ability to maximize a video to a region

### ISSUE THREAD

**Issue by arfmartins** [digitalcreations/MaxTo#388]
The title is self explanatory. Hydravision by AMD had this feature by default. The use case is to maximize Youtube or any video plataform to the top third of my portrait (left) monitor.

**Comment by vegardlarsen** [comment]
Thank you for your suggestion. It comes up a lot; both here and to the support e-mail.

This is an issue we have deliberately not tackled because of its apparent complexity. What we are talking about here is the ability to do windowing operations on "full-screen" applications. The problems are many:

- How do you determine that an application is full-screen, and how do you intercept it as it happens in a generic way?
- Do we need to introduce a window title and/or minimize/maximize/close buttons, or do we just leave it as it is?
- How would the user move such a window to another region? Keyboard shortcuts would probably work. The window itself does not necessarily support being dragged, as it expects to simply be full-screen. It could even have some other functionality when you click and attempt to drag it.
- Most games are also full-screen apps. They capture the mouse pointer. Do we ignore windows that do this? Is it even possible to detect if the mouse pointer has been captured?
- E.g. in browsers; is the fullscreen video window a brand new window, or is it just the same window that the browser uses resized to fit the entire monitor. If the latter; the browser window would "disappear" when a video was opened fullscreen.

Now consider that the answers to these questions will change depending on which application you are looking at. E.g. full-screen VLC does not behave the same as full-screen video playing in Google Chrome.

**Comment by arfmartins** [comment]
Better later than never =)

- How to intercept it in a generic way well that's the major challenge I guess, but I'd be happy even if I needed to flag the apps where I would want the feature;
- I don't understand what do you mean by "introduce window title", I could  always hit "Esc" to go back as I normally do;
- I see no need to support dragging/moving while on full-screen, Hydravision did not supported it either;
- I think that exclusive mode apps that would capture the mouse are beyond the scope;
- I don't know if Hydravision was just a third party software or if it had some kind of low level integration with the driver since it was from AMD, ATI actually, we're talking early eyefinity days. All I know is that it did work and it was application agnostic. In fact MaxTo was a godsend I found when I could not make it work anymore, great little piece of software I can't live without on multi monitor PCs.
- I don't know if this would even be possible, but if there were a way to make a region to behave as a fake virtual monitor.

Thanks for the in depth commentary and sorry for not answering back in a reasonable time frame.

Have a nice weekend

**Comment by vegardlarsen** [comment]
Most of these questions aren't really possible to answer definitively; there are both technical and user experience concerns here. It was more of a list of potential troublesome details we'd have to overcome.

> I don't understand what do you mean by "introduce window title", I could always hit "Esc" to go back as I normally do;

If the window is no longer full screen, there may be an expectation from the end user that they are able to resize/move the window as with other windows. That's way I said we'd have to "introduce" a window title, so the window looks like any other window and can be moved.

> I don't know if this would even be possible, but if there were a way to make a region to behave as a fake virtual monitor.

Not really, as far as I know. I guess it would be technically possible by writing our own video card drivers, but simply attempting this (as you'd have to re-implement most of AMD, nVidia and Intel's drivers to do this) is so complicated I won't even research it. :)

**Comment by 50l3r** [comment]
It would be an incredible functionality.

**Comment by robk9e** [comment]
Guys, 
GIve a try on VDM from iShadow.  It supports full screen and works like a charm. 
https://www.ishadow.com/vdm/
