### ISSUE TITLE
There is a problem with the Logitech Options program.

### ISSUE THREAD

**Issue by hoya7979** [digitalcreations/MaxTo#398]
I mapped certain Logitech mouse buttons and MaxTo keys(win + alt + left) in the Logitech Options program.
And when I clicked the mapped button on the Logitech mouse, the window switch was not executed.
This works well for programs like WinSplit Revolution.
Please check.

**System information:**
- Microsoft Windows 10 Pro [Version 10.0.17763.437]
- MaxTo 2.0.1
- Logitech Options 7.12.43

**Comment by vegardlarsen** [comment]
What did you map here, exactly? Did you attempt to map a specific mouse key to a keyboard combination? That is not going to work; MaxTo overrides the keyboard at the lowest level possible in Windows without writing a hardware driver, and it does not appear to be possible to catch these events for MaxTo.

Can you instead make Logitech Options launch a recipe through the command line?

I don't have this program on my work machine (as I don't have any Logitech devices that work with it), so I cannot test this currently.

**Comment by vegardlarsen** [comment]
I am closing this issue due to lack of feedback.

**Comment by seelenfrieden** [comment]
hello, i have the same issue. Installed the new MX Master 3 and want to switch the windows with the recipe "strg + arrow left (and right) through assigning the command in the LogitechOptions Software to a keypress. But it does not work. With the old MX Revolution and uberoptions it worked. 

What do you mean with “Can you instead make Logitech Options launch a recipe through the command line?“ ?

**Comment by seelenfrieden** [comment]
it would be very helpful to find a way to use the MX Master 3 with Maxto, because the first is a great piece of hardware and the second is a great peace of software. Both I do not want to miss. And to move the windows through the areas with the mouse is a really great user interface.

**Comment by vegardlarsen** [comment]
@seelenfrieden I am afraid I don't really understand what you are trying to accomplish, and the exact steps you take to break this? Can you try giving me a step-by-step to show me what breaks?

**Comment by seelenfrieden** [comment]
yes for sure. sorry for my bad english. I will give it another try: Logitech Options is a software to customize Logitech mouses. The new Logitech MX Master 3 mouse has a lot of buttons. You can assign all possible windows commands to any mouse buttons you want. And so you can also assign a keystroke command to a button. So in Maxto I created a recipe with "ctrl + left or right arrow" to move the window to left and right section. This command I assigned in Logitech option to a mouse button. But if I now press the button nothing happens. If I press the keystroke with the keyboard it works as it should.

**Comment by seelenfrieden** [comment]
@vegardlarsen any chance for help?

**Comment by vegardlarsen** [comment]
I don't think this approach will work. If you can instead a mouse button to run a command line, that could work. I cannot test this as I do not have a compatible Logitech device.

The problem is probably that MaxTo listens for very low-level keyboard events to be able to override default Windows keyboard shortcuts. If Logitech Options sends keystrokes at a higher level (which is most likely), MaxTo will not be able to intercept them.

If you can assign a mouse key to a command, try running something like `%LocalAppData%\MaxTo\MaxTo.exe window move /Direction right" and see if that works?

**Comment by goggi** [comment]
Hi! 
I have a Roccat Tyon mouse and have the same issue. I was not able to add commands to the mouse buttons unfortunately.

Any chance to make MaxTo listen to higher level events also? 
This would be a killer feature as it enables using the mouse to call recipes. 

Cheers!

**Comment by seelenfrieden** [comment]
Unfortunately this is not possible. Any chance for another workaround? Perhaps with a third part app? Or a chance to integrate it into maxto?

It would be so great. Because I really use this control hard in my Workflows. With the old Mx revolution and uberoptions it works. But I want to move to the new Mx master. 

Von meinem iPhone gesendet

**Comment by seelenfrieden** [comment]
Can you please reopen the issue. I think it would be interesting for more people.

**Comment by vegardlarsen** [comment]
It seems so. I am not promising anything here, but I should look into either of these two options:

- allow MaxTo recipes to be triggered by "injected" keystrokes (such as the ones emitted by Logitech Options)
- allow MaxTo to trigger recipes based on mouse events (to completely bypass Logitech Options).

This is unfortunately not going to be a top priority, but hopefully we will get to it.

**Comment by seelenfrieden** [comment]
Oh this will be so great, because without this using the MX Master is worthless for me. Please keep me updated. 

 

Von: Vegard Andreas Larsen <notifications@github.com> 
Gesendet: Freitag, 18. Oktober 2019 12:40
An: digitalcreations/MaxTo <MaxTo@noreply.github.com>
Cc: seelenfrieden <meier@grown-up.info>; Mention <mention@noreply.github.com>
Betreff: Re: [digitalcreations/MaxTo] There is a problem with the Logitech Options program. (#398)

 

It seems so. I am not promising anything here, but I should look into either of these two options:

*	allow MaxTo recipes to be triggered by "injected" keystrokes (such as the ones emitted by Logitech Options)
*	allow MaxTo to trigger recipes based on mouse events (to completely bypass Logitech Options).

This is unfortunately not going to be a top priority, but hopefully we will get to it.

**Comment by seelenfrieden** [comment]
Perhaps a chance with autohotkey app? 

 

Von: Vegard Andreas Larsen <notifications@github.com> 
Gesendet: Freitag, 18. Oktober 2019 12:40
An: digitalcreations/MaxTo <MaxTo@noreply.github.com>
Cc: seelenfrieden <meier@grown-up.info>; Mention <mention@noreply.github.com>
Betreff: Re: [digitalcreations/MaxTo] There is a problem with the Logitech Options program. (#398)

 

It seems so. I am not promising anything here, but I should look into either of these two options:

*	allow MaxTo recipes to be triggered by "injected" keystrokes (such as the ones emitted by Logitech Options)
*	allow MaxTo to trigger recipes based on mouse events (to completely bypass Logitech Options).

This is unfortunately not going to be a top priority, but hopefully we will get to it.

**Comment by seelenfrieden** [comment]
Thanks. For the moment i switched to http://www.soulidstudio.com/ here it works. But would be great to continue work with maxto.

 

Von: Vegard Andreas Larsen <notifications@github.com> 
Gesendet: Freitag, 18. Oktober 2019 12:40
An: digitalcreations/MaxTo <MaxTo@noreply.github.com>
Cc: seelenfrieden <meier@grown-up.info>; Mention <mention@noreply.github.com>
Betreff: Re: [digitalcreations/MaxTo] There is a problem with the Logitech Options program. (#398)

 

It seems so. I am not promising anything here, but I should look into either of these two options:

*	allow MaxTo recipes to be triggered by "injected" keystrokes (such as the ones emitted by Logitech Options)
*	allow MaxTo to trigger recipes based on mouse events (to completely bypass Logitech Options).

This is unfortunately not going to be a top priority, but hopefully we will get to it.
