### ISSUE TITLE
[Feature] Individually editable region-line

### ISSUE THREAD

**Issue by Mrfuyu** [digitalcreations/MaxTo#419]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I just can move a complete region-line and not the line between lines.

**Describe the solution you'd like**
I would like to have the possibility to set different sized regions by moving a horizontal line not just as a whole but also a part of it. Maybe moving the whole line (if there are crossing lines) with shift + click and else just the part between.

For example here is what I mean. I want to click Shift+left mouse to move the red line and only left mouse to move the green line. The black lines should be moveable by both "shortcuts".

![regions](https://user-images.githubusercontent.com/14253537/58576107-cde0eb00-8243-11e9-9295-e9344f653d8c.png)

The corresponding lines could be colored the same so when clicking shift+left mouse on a line that is split into parts of different height it could snap back so it's only one line again. Lines of different colors but same orientation should not be traversable.

**Comment by vegardlarsen** [comment]
Thank you for your request. I really do understand why you want this, but this is not something that we can implement.

The problem lies in the basic way MaxTo constructs its regions. Regions are actually created as split operations:

- Split direction (horizontally, vertically or not split)
- Split distance (as a fraction)
- First and second child "split"

That means that to store your regions as in the image above, MaxTo actually creates a tree that looks something like this:

- Split vertically at 25% distance
  - Split vertically at 67% distance
    - Split horizontally at 25% distance **
      - Top right
      - Bottom right
    - Split horizontally at 25% distance * **
       - Top center
       - Bottom center
  - Split horizontally at 25% distance **
    - Top left
    - Bottom right

This is not just the way it is stored, it is also the way the user interface works. Resizing at the green line only means resizing the *-marked line. Resizing at the red line means resizing at the **-marked lines. In your specific case the distances actually will be the same percentage, but any extra vertical split in here would make this quite a bit more difficult.

We are looking into other methods of dividing your monitor that may be more compatible with the way you are thinking, but they involve changing the entire process MaxTo uses to create its regions.
