### ISSUE TITLE
can't change monitor if task bar is in the way

### ISSUE THREAD

**Issue by raabf** [digitalcreations/MaxTo#42]
Assuming you have the following monitor setup (where T is the Task Bar)

```
+-----------+ +-----------+
|           | | |         |
|     1     | |T|    2    |
|           | | |         |
+-----------+ +-----------+
```
Pressing `Control` + `Windows` + `Left` on focused window, which already touch the Task Bar in screen 2, will not work. The window keeps on screen 2.

Moving a window from 1 to 2 works.

After moving the task bar to the bottom, moving the window from 2 to 1 will work again: 

```
+-----------+ +-----------+
|           | |     2     |
|     1     | |           |
|           | |-----------|
+-----------+ +-----------+
```

Environment
==========

 + Windows 8.1
 + MaxTo 2014.12.0.0

**Comment by vegardlarsen** [comment]
@raabf Thanks for reporting this. The problem here is that the algorithm for where to move the window only looks immediately around the edges of the working area for the next available region in that direction. It never occured to me that the working areas would be split in this way. So it appears that the algorithm for moving these windows need some fine-tuning.
