### ISSUE TITLE
Swap window with an tile hotkeys are missing

### ISSUE THREAD

**Issue by raabf** [digitalcreations/MaxTo#45]
If do not only want to move a window to another tile, but also want to swap the windows is actually not fast possible at the moment.
If you want to swap with left side you has to press: `Control` + `Windows` + `Left` then `Control` + `Windows` + `Page-Up` and at least `Control` + `Windows` + `Right`. Quite many keystrokes. So an additional swap window hotkeys would be nice.
Just add an additional modifier for that like  `Control` + `Windows` +`Shift` + `Left`.

**Comment by vegardlarsen** [comment]
So you are suggesting that this would swap with the top window in the region you are moving to? Not a bad idea.

This is definitely a feature I will keep in mind for later.

**Comment by raabf** [comment]
Yea. With this feature you can define a "Main Tile" (for yourself) which is big in size. So you can fast switch windows from tiles which are smaller so you can working more comfortable on the actual needed window.
Or you can fast order your windows in a way you find it more clear.

**Comment by vegardlarsen** [comment]
@raabf I have just taken a stab at implementing this. This actually works really well, but there is a caveat of sorts. When you swap a window with another, all the windows in that region is swapped with the single window you are moving.

Say you have three windows: A, B, C, with A and B in the left region and C in the right. C is on top, and has focus. When you press `Control`+`Windows`+`Shift`+`Left`, both A and B are now in the right region, while C has taken over the left region. Focus will still be on C.

The reason for this is that it seems to be impossible to determine the ordering of the windows in the region you are moving to. Mostly because they may not be on top. So the compromise here is to move all of them.

This feature will be in the next release.

**Comment by raabf** [comment]
very nice :-D
