### ISSUE TITLE
Thunderbird won't fit to the region

### ISSUE THREAD

**Issue by nepumax** [digitalcreations/MaxTo#459]
**Describe the bug**
I use MaxTo on an Ultrawidescreen monitor (2560x1080). I separated it into two regions (1600x1002/960x1002). I use Firefox on the left and Thunderbird on the right region. While Firefox always starts in the exact borders, Thunderbird doesn't. I have to drag it to the region borders to fit. When I reopen Thunderbird, I have to do it again.

**To Reproduce**
See above.

**Expected behavior**
It should fit.

**Screenshots**
![Right after starting.](https://s18.directupload.net/images/190822/bc5koz3k.jpg)
Right after starting.

![After fitting to region borders.](https://s18.directupload.net/images/190822/goldkb36.jpg)
After fitting to region borders.

**System information:**
 - Windows version: 10, v1902
 - MaxTo version 2.0.1

**Comment by vegardlarsen** [comment]
Thank you for getting in touch. 

If I understand you correctly, the main complaint here is that Thunderbird does not fit into a region when it initially starts?

If that assumption is correct, this is by design. MaxTo does not (currently) force applications to do things unless you maximize them or use the keyboard shortcuts.

That said, in version 2.1 you will be able to create recipes that trigger on programs starting, and forcing windows into the closest region automatically.

If my assumption above is wrong, feel free to let me know and I'll re-open this issue.

**Comment by nepumax** [comment]
But the thing is, Firefox fits directly. I never have to reassign Firefox. Why does Firefox stay in the region and Thunderbird doesn't?

**Comment by vegardlarsen** [comment]
This is more of an application choice; as a programmer you can choose where your window should be placed initially. Firefox may have logic in it that places the window where it was the last time, and Thunderbird may not, or it may have faulty logic, or it may let Windows place the window automatically.

This issue is also present with Google Chrome, but it also happens if you just use the built-in Windows half-monitor sizing, so it isn't really related to MaxTo.
