### ISSUE TITLE
Not working for newest Microsoft Edge Dev (Chromium)

### ISSUE THREAD

**Issue by watermarkhu** [digitalcreations/MaxTo#463]
After an update of the new Microsoft Edge browser the Maxto stopped to work with the browser.
Issue encountered from Edge Version 78.0.244.0 (Official build) dev (64-bit) 

Issue might also occur on newest Chrome versions looking at the [issue tracker of WindowGrid](https://bitbucket.org/joshua_wilding/windowgrid-binaries/issues/52/new-microsoft-edge-chromium-dosnt-work)

**Comment by vegardlarsen** [comment]
I have tried Edge in that version, and it appears to have the same issues here. MaxTo however works well with the latest version of Chrome.

Do you know in which version the issue was introduced? I have submitted feedback to the Edge team, because it does not initially appear to me that this is MaxTo's fault, but I may be wrong.

**Comment by watermarkhu** [comment]
I would say 78.0.244.0, but I'm not sure. I reported it when it when I was on 78.0.244.1, and the problem existed then only a day or so.

**Comment by vegardlarsen** [comment]
I am still making no headway on this. It seems Edge is not "publishing" window events for their window. Examining their window in Spy++ yields no messages, but the window itself seems to qualify for MaxTo integration.

I have asked MSEdgeDev on Twitter to look in on this issue and open up a dialogue.

**Comment by vegardlarsen** [comment]
I am closing this in favor of #473. It appears this is an issue with every Chromium browser starting from version 78.

**Comment by vegardlarsen** [comment]
It appears my previous message is a bit inaccurate. Chromium does publish window messages for their windows; however, the CBT and CallWndProc hooks do not receive any notifications from any of their windows, and therefore no MaxTo functionality initializes.

This is all very strange, because I can see the window messages in Spy++, which means that Spy++ is able to get hold of them in some manner.
