### ISSUE TITLE
Powershell scrollbar outside of region 

### ISSUE THREAD

**Issue by baalimago** [digitalcreations/MaxTo#470]
**Describe the bug**
When maximizing to a region, the scrollbar gets put outside.

**To Reproduce**
1. Open up powershell, add it to region which is on the left.

**Expected behavior**
To have scrollbar within the region.

**Screenshots**
https://i.imgur.com/gWYaCbI.png

**System information:**
 - Windows version: 10
 - MaxTo version: 2.0.1

**Comment by vegardlarsen** [comment]
I have tracked down and solved this issue.

Console windows (`conhost`) such as command prompt and Powershell windows do not particularly like to be resized. If you tell them to go somewhere, they will resize themselves to be slightly bigger to make room for their scrollbars.

We have fixed this by taking into account the font used by the console window, the number of rows and columns they can fit, and if they do or do not have a vertical scrollbar.

Horizontal scrollbars are a different beast, though. In Windows 10, Microsoft changed console windows to have word-wrapping at the end of line by default. This setting makes it so that there should never be a horizontal scroll-bar while it is on, and it is on by default. On older Windows versions, the scrollbar may appear.

Since the word-wrap setting is not exposed through any programming model, we cannot detect if it is on or supported, so by default we will have a similar bug for the horizontal scrollbar if you disable word-wrap on Windows 10.

The changes I have made today will be in the first preview of 2.1.0.
