### ISSUE TITLE
MaxTo needs hotkey to bring up the Change Regions screen

### ISSUE THREAD

**Issue by yamlCase** [digitalcreations/MaxTo#473]
I am a "mostly keyboard" user who likes to use hotkeys for everything (I'm sure there's more of us out there!).  I also like to change my regions frequently depending on what kind of apps I'm bringing up.  It would be really awesome if there was a hotkey to bring up the "Change Regions" screen with a hotkey to help keep my eyes from having to hunt down the little icon in the taskbar each time.  Thanks!

**Comment by vegardlarsen** [comment]
I like this idea. Sorry it has taken me so long to say so. This is definitely something that we will do, but probably after 2.1.

**Comment by bmspcsd** [comment]
I agree this would be very handy. IMO it would be better to bring up the "Load Preset" screen (the one that shows a graphic representing each layout) rather than the "Change Regions" screen. The "Load Preset" popup is already about the right size and layout for this purpose. This would allow the fastest switching of layouts by simply hitting the hotkey and then selecting the desired layout from the popup. Going to the "Change Regions" screen requires more clicks and also kind of breaks concentration when you are in the middle of something since it "frosts" the entire screen. Just my 2 cents.

**Comment by vegardlarsen** [comment]
The plan is to allow bringing up most parts of the user interface using commands:

- change regions
- apply preset (on a specific monitor)
- settings
