### ISSUE TITLE
Main and alternate regions & proper maximizing

### ISSUE THREAD

**Issue by Reapsert** [digitalcreations/MaxTo#486]
I have been using the older, more classic version of maxto for a while now. But recently somehow a maxto update was forced onto me and now all of a sudden the software completely sucks for my natural, mainly mouse-based, usage. Moving windows in different ways using keyboard shortcuts just is not natural to me one single bit...

Shift draging onto regions works fine, but there are only one set of regions, where are the settings for alternate regionss that I LOVED?! I can not stand moving windows to different locations using window keys. And even when I do it only seems to use halves or quads, not the perhaps smaller regions I get when shift dragging windows. 

And even when using windows+up does not really maximize a window. Some times it does not work at all even though a window is in a top quarter, and when it does "work" it is not really maximized but a minimized window scaled to fit the screen. This results in ugly borders and messes up some programs, not even mentioning trying to close a program with the cursor in the top right of a window just accidently rescaling the window instead. 

And why on earth does double clicking the top bar or pressing the maximize button fit the window to the region? Surely those actions should be reserved for proper maximizing of a window to the entire screen? If I wanted the window fit to a region I would just have shift dragged it there. Perhaps switching to shift maximizing and shift clicking the topbar could do that and leave the more natural windows behaviour as is. Or at least give users the option to chose which they prefer.

You had such an amazing, easy and simple software before 2.0 that I would gladly have paid the double amount for. And now you have ruined it for me. If you do not fix the behaviour or at least release older versions for download then I will sadly just have to find a new program that works more like yours did before...

**Comment by vegardlarsen** [comment]
> And even when using windows+up does not really maximize a window. Some times it does not work at all even though a window is in a top quarter, and when it does "work" it is not really maximized but a minimized window scaled to fit the screen.

Windows+Up with MaxTo is not meant to be used to maximize a window. It is meant to place the current window into the closest region above it. Windows should behave exactly as they did in the previous version of MaxTo, its state will remain "restored" when it is put into a region (because otherwise Windows cannot handle it).

> And why on earth does double clicking the top bar or pressing the maximize button fit the window to the region? 

This was the default setting in previous versions of MaxTo as well? You could change it to run in "Passive mode", which is a feature we have removed, and which is coming back, but the default behavior is the same.

> You had such an amazing, easy and simple software before 2.0 that I would gladly have paid the double amount for. 

The previous version is still [available for download](https://maxto.net/release), and you can stay on that version if you want to. However, you will not be getting upgrades and new features.

I am closing this issue, as it is not really actionable on our end.
