### ISSUE TITLE
Make regions scalable

### ISSUE THREAD

**Issue by tpk109** [digitalcreations/MaxTo#489]
As  I understand now the regions are fixed in size. 

I quite like the Win10 feature that two windows on one screen can be connected and if you enlarge one window the other one gets smaller.  I would love to have 4 regions on the screen and be able to move the dividing lines between the windows horizontally and vertically.

**Comment by vegardlarsen** [comment]
This is absolutely something we would like to support in one form or another, however, there are technical and user experience reasons we haven't done it yet.

Technically, we would need to re-implement the same functionality as the current region editor, just using windows instead. That would be quite a difficult feat in itself. Because of its tree-structure, that could prove to be difficult.

User experience-wise, would we persist the changes to your regions when you make them this way, or would it just revert after a reboot? At the moment, any changes to the active regions is persisted, and I think it would have to work that way here as well.

What happens when you resize a window that doesn't have another window in the region next to it? Do we still scale the regions? For consistency, I think the answer has to be yes.

**Comment by yamlCase** [comment]
I'm all for this.  I have an ultra-ultrawide setup with the screen split in 6.  My middle area is either "browser + browser" in even split, or "console + IDE" in roughly 1/3 + 2/3 split.  I oftentimes switch between the two depending on what I'm doing throughout the day.  MaxTo 1.x made this easy with alternate regions, but I'm forcing myself to use MaxTo 2.x.

Aquasnap has an "AquaGlue" feature that acts on the individual windows which I think would be an alright way to do this.  The two side-by-side windows can have their widths adjusted without disturbing the region underneath.  Going this route would satisfy my need for alternate regions.

![2020-01-18_13-21-43](https://user-images.githubusercontent.com/27447701/72669375-a15a2900-39f6-11ea-8841-ce9eb74cfc73.gif)

**Comment by vegardlarsen** [comment]
@yamlCase I am aware of this feature, and it is something we are looking to do in some way or another.

**Comment by vegardlarsen** [comment]
This is actually the same as issue #117. Closing this one as a duplicate.
