### ISSUE TITLE
Recipe improvement ideas: rearranging ingredients, launch to region, idempotent launch, minimize all

### ISSUE THREAD

**Issue by bmspcsd** [digitalcreations/MaxTo#496]
I really like the Recipes, but have a few ideas for improvement:

**1. Allow rearranging ingredients.** If there is a way to do this now, I can't figure it out. The most intuitive way would be to just drag and drop in order to change the order that the ingredients run. An up/down arrow would work too although it would not be as easy to use.

**2. Ability to specify a region to launch a program in.** Although this can be done in 2 steps now using Launch and then Move, it would be very handy to be able to launch programs directly into a specific region.

**3. Launch if not running, maximize if already running.** Basically what I would like to accomplish is to start with a disorganized array of windows, hit a recipe hotkey, and have a predefined neatly arranged workspace for a specific task. It would be nice if in addition to Launch, there were an option that Launched or simply moved an existing program window if one is already open. This option would be idempotent where Launch is not.

**4. Add an ingredient to minimize all open windows.** I would use this as the first step to any "workspace management" recipes that launch and arrange a specific set of programs.

Thanks!

**Comment by vegardlarsen** [comment]
@bmspcsd Thank you for the feedback. I'll just get right to your points.

1. Completely agree. We haven't done this yet because we've been having a bit of trouble with the component we use that lists them, but we will definitely do this. Probably sooner rather than later.
2. This is technically quite hard, and would work poorly for quite a few programs. Since we have the option to move after launching, I don't think this is a big deal.
3. This is a very good idea; we could probably do this as an extension of the current Launch command. E.g. a checkbox saying "Abort launch if program is already running"?
4. I like this.

We're going to have to break these items (1, 3 and 4) out into separate issues, so feel free to file separate issues for these items with a reference to this issue.

**Comment by bmspcsd** [comment]
I can see your point on 2 not being necessary. Thanks for considering the others. I created separate issues for each and linked them.

**Comment by vegardlarsen** [comment]
Thank you. Closing this one as issues with multiple different action points are very hard to track progress on. :)
