### ISSUE TITLE
Problem with Recipes

### ISSUE THREAD

**Issue by indigodreamer** [digitalcreations/MaxTo#505]
This is in relation to the second issue described here [https://github.com/digitalcreations/MaxTo/issues/494](url)

I am trying to set up a recipe which will open particular Google documents in Firefox and place them in regions on my monitor. I've simplified things for the purpose of this bug hunt, to a recipe with two ingredients; open the Google Document in a new Firefox Window and then move the window. 

Using release 2.0.1 I was typically finding the ingredients appearing to work out of sequence, so that the foreground window would be moved before Firefox was launched. 

I thought I would try the latest Alpha release just in case one of the other fixes had improved things.  Now, using 2.1.0-Alpha2 Firefox opens the document, no window is moved and I get an error message "Object reference not set to an instance of an object". 

Here's the relevant section of the logfile:

2019-11-25 19:56:05 [Core@2.1.0.594] [Information] [MaxTo.Core.Keyboard.RecipeExecutor] Executing recipe '"Test"' with 2 ingredients
2019-11-25 19:56:05 [Core@2.1.0.594] [Warning] [MaxTo.Core.Keyboard.RecipeExecutor] Received exception from command request 1 while executing '"Test"'. Aborting.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MaxTo.Core.Native.Windows.SystemWindowManager.set_ForegroundWindow(ISystemWindow value)
   at MaxTo.Core.Commands.LaunchCommand.<Execute>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MaxTo.Core.Commands.CommandExecutor.<Execute>d__3`2.MoveNext()
2019-11-25 19:56:05 [Core@2.1.0.594] [Information] [MaxTo.Core.Recipes.DefaultRecipeController] 1 recipes was executed (0 succesfully)

Here are screenshots of the ingredients in Version 2.0.1. The linked document is a virtually empty test document created for the purpose. 
![MaxTo Recipe(1)](https://user-images.githubusercontent.com/57566733/69574525-4b51a200-0fc0-11ea-831b-d8b540784926.PNG)
![MaxTo Recipe(2)](https://user-images.githubusercontent.com/57566733/69574535-53a9dd00-0fc0-11ea-846a-487743cd3de0.PNG)
![MaxTo Recipe(3)](https://user-images.githubusercontent.com/57566733/69574551-5efd0880-0fc0-11ea-8ff2-54a45cc04f71.PNG)

Thanks in advance for any help.

**Comment by vegardlarsen** [comment]
Sorry for the slow response on this, I have been sick this week.

Unfortunately, the problem here is mostly the same as before; when you launch Firefox, the process you are starting will see that an existing instance of Firefox is already running, and it will send a signal to that process, and then immediately shut itself down. The pre-existing Firefox process will then get to work opening a window (which MaxTo will not wait for, it could happen after the next step of the recipe runs).

The error message only happens because you have checked the "Bring to front" checkbox, because MaxTo ended up with no window for that process. I have turned this mysterious error into a warning message instead that describes what happened a bit better.

That does not change the fact that currently, what you are trying to do (at least in this manner) is not possible to do without changing what you are doing. I would try with other flags to Firefox (e.g. `-new-instance`, `-no-remote`, or maybe `-foreground`, found in [docs](https://developer.mozilla.org/en-US/docs/Mozilla/Command_Line_Options)). These things would use more memory when running Firefox, but could potentially get it to work for you.

**Comment by heystenner** [comment]
@indigodreamer In case you are still looking for a solution:

I had the same issue and solved it by first maximizing the Firefox window on the current screen and then moving it to the designated are.

I'm also using -new-window when I load pages into Firefox:

For example: `Firefox.exe -new-window https://github.com/`

**Comment by indigodreamer** [comment]
Thank you. I shall try what you suggest.
