### ISSUE TITLE
Impossible to execute formula

### ISSUE THREAD

**Issue by lachap1234** [digitalcreations/MaxTo#529]
**Describe the bug**
Installed and bought the program yesterday, now I just started my computer this morning and used my shortcut to change the way my display are set. 
I get and error which says "the key given is absent from the dictionnary" are we talking here about the recipe I created yesterday or about my license key?

**Screenshots**
![2020-01-16 08_21_49-Window](https://user-images.githubusercontent.com/18574829/72528963-44b20f00-383a-11ea-8555-4a33d2e4e251.png)

**System information:**
 - Windows version: 10
 - MaxTo version 2.0.1

**Comment by vegardlarsen** [comment]
This is a problem with the recipe you created, but the error message is very poor. This should be fixed in the preview releases (2.1.0-alpha.3), instead showing an error message that makes sense.

If you can get me a copy of the recipe you created (open `%AppData%\MaxTo\config.json` in a text editor and look for it), I'll probably be able to tell you more specifically what is wrong.

**Comment by vegardlarsen** [comment]
Closing due to lack of feedback.
