### ISSUE TITLE
Fill Empty Space From Taskbar When Using Surround

### ISSUE THREAD

**Issue by paul-shell** [digitalcreations/MaxTo#540]
**Is your feature request related to a problem? Please describe.**
With three monitors in surround, the taskbar at the bottom would span the entire bottom which is too much. NVidia has a setting to only show on the center monitor. Which works, but there's still empty space where the spanned taskbar would be.

**Describe the solution you'd like**
A setting to set my own usable screen space. Or some way of confining the taskbar to one of the virtual monitors width, without affecting others.

**Describe alternatives you've considered**
I've tried auto-hiding the taskbar, but that makes the clock stop even though the bar itself never goes away. Which is driving me nuts.

**Additional context**
You can see the bottom empty space on the two other monitors where the taskbar would normally be.
![explorer_b7pAYe34n5](https://user-images.githubusercontent.com/11514475/75190422-deac8780-5715-11ea-8fe2-483d5e59d5ce.png)

**Comment by vegardlarsen** [comment]
Thank you for your request @paul-shell. When I first started thinking about this last night it seemed like a completely reasonable request, until I considered the fact that the usable work area for a single monitor would no longer be a rectangle.

Because of the way nVidia Surround works (joining multiple, equal-resolution monitors into one), the combined monitor resolution is always a rectangle. If you choose to only display the taskbar buttons on one monitor, it can't "unreserve" the space on the other monitors, as Windows considers them a single monitor and Windows only accepts a rectangular working area.

I think you'll need to disable nVidia Surround; then you can get this the way you want it. In Windows there is a setting to only show the taskbar on the primary display:

![image](https://user-images.githubusercontent.com/436508/75221276-c2562c80-57a1-11ea-905b-2260df151fa2.png)

On your picture it seems your leftmost monitor is the one with the taskbar; if that is the case, you can perhaps join the two right-most monitors to get a unified surface on those.

I am closing this as this is not something we can fix.
