### ISSUE TITLE
Problem with paint.net

### ISSUE THREAD

**Issue by hyzhangzhy** [digitalcreations/MaxTo#554]
**Describe the bug**
With MaxTo enabled, I can not move, maximize paint.net window, but I can resize it by dragging its boarder. 

https://www.getpaint.net/

I am using MaxTo 2.1.0.beta1, paint.net 4.2.10, win10 x64.

**Comment by vegardlarsen** [comment]
@hyzhangzhy I have just downloaded paint.net (from the website, not the Microsoft Store), and I can confirm that it doesn't work that well with 2.1.0-beta.1.

It does however work with 2.1.0-beta.2 (which isn't ready yet), so I am closing this as fixed in that release. You will automatically get updated to beta.2 when it is released.
