### ISSUE TITLE
Prefix shortcuts

### ISSUE THREAD

**Issue by yacoob** [digitalcreations/MaxTo#559]
I'd like to ask whether maxto could be configured to use prefixed shortcuts. If you've ever used screen, tmux or Moom, you'd know this model of shortcuts. Essentially, you need to press a special combination (a prefix) first and then a shortcut that actually does something. This way, instead of trying to find the right `win+alt+ctrl+shift+some_unused_key` combinations that won't clash with an arbitrary piece of software's keybindings, I only need to come up with a unique prefix, and then relegate the rest of functionality to normal keys. For example, in tmux, the prefix is `ctrl-b`. In order to create a new window, you need to press `ctrl-b` and then `c`.  I've configured moom to use `ctrl-=` as prefix, and then can press `ctrl-= 1` to move a window to left half of the screen.

This is purely a convenience thing. I'm blisfully unaware how hard it'd be to create a prefix keybind like that under Windows - hence, opening this bug as a question :)

Thanks for considering!

**Comment by vegardlarsen** [comment]
This is something that we are considering for a future version. We've previously put it off because the native keyboard shortcuts system ([`RegisterHotKey`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey)) doesn't support it.

At the moment we are using our own low-level keyboard hook to implement keyboard shortcuts; and that method of implementation would support it.

**Comment by vegardlarsen** [comment]
Closing this due to our new policy of trying to keep only issues we know we will look at open.
