### ISSUE TITLE
Recipe '"Show highlight on Virtual Desktop change"' was stopped to prevent infinite loops

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#568]
**Describe the bug**
When changing virtual desktops, the recipe will not be executed reliably.

**To Reproduce**
1. Create recipe to highlight regions on virtual desktop change
1. Change virtual desktops multiple times

**Expected behavior**
Will always be executed, even when waiting some seconds between changes. What actually happens is that for whatever reason, the infinite loop detection kicks in.

**System information:**
- Windows version: Windows 10 Version 1909 18363.836
- MaxTo version: 2.1.0-beta1

**Additional context**
```
2020-05-20 15:41:38 [Core@2.1.0.644] [Warning] [MaxTo.Core.Keyboard.RecipeExecutor] Recipe '"Show highlight on Virtual Desktop change"' was stopped to prevent infinite loops.
```

**Comment by vegardlarsen** [comment]
I agree this is somewhat annoying. Keyboard triggers are whitelisted from this infinite loop detection, because they are always the result of user input, and thus cannot go into an infinite loop.

The same can not be said about the virtual desktop changed trigger; e.g. the window move command can cause this to trigger, and you would quickly end up in a situation where you can get an infinite loop.

In 2.1.0-beta.1, the detector is quite simple; every time we execute a recipe, we store the time it was last executed and a counter. If the recipe is executed again within 5 seconds, we increase the counter. If the counter reaches 10, we block further execution. If the recipe is run after the 5 seconds has expired, the counter resets. 

For 2.1.0-beta.2 I have lowered the timeout to 2 seconds. That should still be enough time to catch it if a recipe generates a loop, but much harder to trigger when browsing through virtual desktops manually.

**Comment by thewavelength** [comment]
Can you make this amount/time configurable? 2 seconds still seem to be too high for my personal usage behavior. I am a visual guy and am detecting the correct virtual desktop by seeing the highlighted regions. Thus it can happen that I am cycling through them quickly to find the correct one.
