### ISSUE TITLE
Ejection of MaxTo.Hook.x64.dll is not reliable on close

### ISSUE THREAD

**Issue by thewavelength** [digitalcreations/MaxTo#571]
**Describe the bug**
I am testing between different MaxTo versions (alpha, beta, stable). Therefore, I'm closing, replacing and restarting MaxTo a lot recently. I detected sometimes that MaxTo.Hook.x64.dll couldn't be deleted when I wanted to overwrite MaxTo with yet another version. Throwing Sysinternals Process Explorer at it, it seems like MaxTo.Hook.x64.dll isn't being ejected successfully from some processes. On the screenshot you can see that this happen for 2.1.0-beta1 as well as prior versions. I am running in elevated mode.

**To Reproduce**
I didn't found a fully reproducible way to force this behavior.

**Expected behavior**
Should eject from all processes when closing.

**Screenshots**
![dll](https://user-images.githubusercontent.com/1430997/82537725-cbf5f300-9b4a-11ea-9a90-80eb89bb018d.png)

**System information:**
- Windows version: Windows 10 Version 1909 18363.836
- MaxTo version: 2.1.0-beta1

**Additional context**
No entries in log file regarding this DLL.

**Comment by vegardlarsen** [comment]
If you know of a method to actually unload a DLL injected using `SetWindowsHookEx` reliably, I would love to hear about it :)

The problem is that since the DLL is loaded into the existing processes by the system, unloading it is not really possible.

[Some](https://stackoverflow.com/questions/3164190/unloading-dll-from-all-processes-after-unhooking-global-cbt-hook) [research](https://docs.microsoft.com/en-us/windows/win32/winmsg/using-hooks?redirectedfrom=MSDN#system_events) [into](https://stackoverflow.com/questions/31253796/does-unhookwindowshookex-unload-the-library-from-the-hooked-application-for-a-th) this has been done. (I just barely noticed that the first link is me asking SO a question 10 years ago about this exact issue)
