### ISSUE TITLE
Passive Mode Shift Hold Down Snap In does not work

### ISSUE THREAD

**Issue by farewarr** [digitalcreations/MaxTo#587]
**Describe the bug**

**To Reproduce**

1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**System information:**
- Windows version: 
- MaxTo version: 

**Additional context**

Version 2.1.0 Beta2

I have the feature turned on. When I place MaxTo in Passive Mode, I hold down a window and the shift key and move to snap in and it does not work.

**Comment by vegardlarsen** [comment]
Thank you for your report. Can you please elaborate a bit on exactly what does not work?

**Comment by xGBHxPegasus** [comment]
Just to add to this, just upgraded to the Version 2.1.0 Beta2 and found the passive mode does work but not as described. 

It seems for me its doing it as a Toggle not as a hold. I can press shift once, snap everything in place, then press it again and it will not snap in place. Hold doesn't seem to do anything apart from toggling on and off.

**Comment by vegardlarsen** [comment]
I think there may be a misunderstanding here in how Passive vs Active mode is meant to work.

## In active mode
- Windows maximize into a region. 
- If you hold Shift while maximizing, the window maximize normally.

## In passive mode
- Windows maximize normally by default.
- If you hold Shift while maximizing, the window will be put into a region.

Passive/active mode does not currently affect what happens when you Shift+drag windows. This is because we would need to change what happens by default when in active mode (you won't need to hold Shift to drop a window into a region), and this would be a breaking change. We are therefore holding that of for version 3.0 (major version bump).

Does that clear it up?
