### ISSUE TITLE
Unexpected window movement between regions

### ISSUE THREAD

**Issue by rswrz** [digitalcreations/MaxTo#607]
**Describe the bug**
My region layout is two big regions side by side in first row on top and three small regions in second row on bottom.

```
[   0,0   ][   0,1  ]
[ 1,0 ][ 1,1 ][ 1,2 ]
```

Using keyboard shortcut to move Windows to top/right/left/bottom region does not work correctly with this kind of layout.

Let me give an example:

1. Window is in `0,0` region
2. Pressing Shortcut for _move-right_ moves the window to `1,1` but it should be moved to region `0,1`
3. To get the window moved from region `0,0` to `0,1` I have to _move-right_ (which moves bottom-center `1,1`) and then _move-up_ to `0,1`.
4. If I want the window moved from region `0,1` back to region `0,0` I have to _move-left_ to `1,1`, _move-left_ to `1,0` and finally _move_up_ to `0,0`.

**To Reproduce**
1. Create a region setup like described above
2. Set keyboard shortcuts for window movement
3. Try to move window _naturally_ through the regions (up/right/left/down)

**Expected behavior**
When in region `0,0` in my example, the window should move to region `0,1` when the keyboard shortcut for _move-right_ is pressed. The same for _move-left_ when in region `0,1` the window should move to `0,0`

**Screenshots**
![image](https://user-images.githubusercontent.com/9085379/92077935-ad47ff00-edbd-11ea-8798-261b2a6e1ce9.png)

**System information:**
- Windows version:  Windows 10 - 1909 (OS Build 18363.1016)
- MaxTo version: 2.0.1

**Comment by vegardlarsen** [comment]
Thank you for the report. We are aware that this behavior is somewhat strange. We've struggled with finding a model for moving here that feels natural (I believe I have tried at least 5 different approaches, not all made it into releases). The model we have settled on here, is sorting by center to center distance between the regions (after filtering away anything that is in the opposite direction). In your case, this probably gives an unnatural result, because the distance is shorter for the [1,1] region than the [1,0] region.

I would be happy to change this if we can find a procedure that would feel more natural.
