### ISSUE TITLE
More comprehensive help file/page

### ISSUE THREAD

**Issue by llinfeng** [digitalcreations/MaxTo#61]
The new release worked greatly. Thanks @vegardlarsen for committing to this product.

Had there been one thing that could be improved, it must be the help-file. So far, I have found no explanation to the following questions:
1. How the "alternative" region would interact with the "main" region? Does one of them has an "overlapping" privilege?
2. How does the "passive mode" works?
3. What does "highlight regions" mean? Upon clicking on such option, I saw nothing but one black box/window per screen.
4. What does "Switch to next window in region" mean?
5. What does "Switch to previous window in region" mean?
6. How exactly are "window" and "region" defined?

All the best, 

-Linfeng

**Comment by vegardlarsen** [comment]
Yes, I am aware that we are lacking in the documentation department. It is something that I definitely want to fix for the future. At the moment, I can answer your questions quickly:

1. The main and alternate regions do not interact. They are simply two sets of rectangles that your windows will be resized within. 
2. Passive mode works by flipping the mode of how MaxTo works. Instead of having to press Shift when you want the window to maximize to the entire monitor, you will have to press Shift when you want to limit its size to a region when maximizing.
3. Highlight regions shows you where your regions are.
4. Switch to next and previous window is like Alt+Tab for the region with focus.
5. A region is a rectangular part of your screen. A window is any application window.

**Comment by llinfeng** [comment]
Great, this is helpful.
