### ISSUE TITLE
Windows Key left or Right Arrow on Desktop

### ISSUE THREAD

**Issue by Sterling177** [digitalcreations/MaxTo#623]
( no windows active ) when hitting the windows Key and Arrow left or right the desktop is treated like a window and the desktop snap s to each sector - the only way to fix this is to log out and back in.

**Comment by vegardlarsen** [comment]
@Sterling177 Thank you for the report. I've solved this issue now, with a compatibility shims update. You should be able to go into Settings, Compatibility, and hit "Check for updates" to get this update in about 1 hour (due to our website caching this API call). The fix will take effect after you've restarted (or signed out).
