### ISSUE TITLE
Addobe compatability shim messing up maxto's ability to execute recipes. 

### ISSUE THREAD

**Issue by kaffien** [digitalcreations/MaxTo#627]
The documentation to disable the compatibility shim with adobe is null and void. 

MaxTo is no longer installed into the program files directory.  Searching for  shims.xml 
turns up nothing.  

How do i disable  this compatibility shim? I've disabled the adobe sandbox features. 
I have also disabled adobe under the compatibility section of Maxto 2.01

Is this fixed perhaps in one of the betas?

**Comment by vegardlarsen** [comment]
Thank you for the feedback. I have updated the compatibility shim description with up to date instructions. It should be visible within a few hours (due to caching).

If you've done as you say, the compatibility shim should be disabled after you restart your computer. I am closing this issue as I assume I've fixed the root issue, let me know if I am mistaken.
