### ISSUE TITLE
Mikrotik Winbox crashes when pressing buttons on dialogue

### ISSUE THREAD

**Issue by Nozlaf** [digitalcreations/MaxTo#645]
I noticed that winbox kept crashing when I pressed a dialogue button, found a old issue with mikrotik with maxto decided to disable maxto and it resolved the issue

**To Reproduce**
1. open winbox and connect to a device
2. click on system, routerboard press ok
3. winbox will vanish

**crash report**
Faulting application name: winbox64.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: winbox64.exe, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc000041d
Fault offset: 0x000000000002eca0
Faulting process ID: 0x840
Faulting application start time: 0x01d6b311682dd610
Faulting application path: C:\Users\Nozlaf\Downloads\winbox64.exe
Faulting module path: C:\Users\Nozlaf\Downloads\winbox64.exe
Report ID: 5c5a2afe-916c-488f-94bd-7508361278e1
Faulting package full name: 
Faulting package-relative application ID: 

**Expected behavior**
expect that winbox should not vanish at this point

**System information:**
- Windows version: 1903 Build 18362.1139
- MaxTo version:  2.10

**Comment by vegardlarsen** [comment]
@Nozlaf Thank you for reporting this. I've made changes to the compatibility shim so this will work in a little while. It takes a few hours to roll this out to our website due to caching; but once you've updated your compatibility shims in an hours time or so, it should work.

For reference; the cause was that WinBox created or activated a window `routeros_dbl_canvas`, which did not react well to MaxTo, essentially the exact same behavior as we saw earlier.
