### ISSUE TITLE
MS Outlook Persistently Transparent

### ISSUE THREAD

**Issue by allan-shoup** [digitalcreations/MaxTo#656]
**Describe the bug**
MS Outlook app window is persistently transparent.

**To Reproduce**

1. Turn the Window transparency setting off:
![image](https://user-images.githubusercontent.com/7842213/99118545-5af53c80-25bd-11eb-92fb-5916afef1918.png)
2. Open Microsoft Outlook
![image](https://user-images.githubusercontent.com/7842213/99118973-19b15c80-25be-11eb-8892-142f56381385.png)
3. Click and drag title bar to reposition window (note that the problem only presents itself when the reposition is initiated from the mouse. Pressing Alt + Space, M before moving the window does not present the problem).
4. Release the mouse button after the window has been moved. Window is now transparent.
![image](https://user-images.githubusercontent.com/7842213/99119771-60538680-25bf-11eb-81c7-b0494c6af892.png)
Note that the window remains transparent, even after maximizing/minimizing. This problem is not present with any other application that I've found. If I quit and restart Outlook, the window is no longer transparent. If MaxTo is not running, the same process does not result in the window becoming transparent.

**System information:**
- Windows version: 2004 (OS Build 19041.572)
- Outlook version: 2008 (Build 13127.20408); Microsoft Outlook for Microsoft 365 MSO (16.0.13127.20402) 64-bit
- MaxTo version: 2.1.1

**Comment by vegardlarsen** [comment]
@allan-shoup I've just received a very similar report to yours, but regarding Microsoft Excel. Is that the case on your machine as well?

**Comment by Michael5122** [comment]
Same issue happens sometimes every day both with word and internet explorer :/ started happening couple of weeks ago...
![image](https://user-images.githubusercontent.com/65541736/99155928-d853a680-26bc-11eb-94f9-2c9cfbe626e2.png)

**Comment by Michael5122** [comment]
Guys!! Maxto is getting ungry these days? whats going on? Now every time i move a windo it reduces it in a small dimention

![image](https://user-images.githubusercontent.com/65541736/99157032-11dcdf80-26c6-11eb-8a69-67e3ffe6d672.png)
  
Please help! Thanks!

**Comment by manuelhuber** [comment]
I also have the transparency issue in 2.1.1 (similar/same as in 2.1):
It happens when I resize windows. With this popup in Rider it happens consistently. The first resize is fine but when I resize a second time it goes transparent:
https://youtu.be/Zh_dOyphYq8
But also chrome and other windows become transparent when I resize them
![2020-11-15 14_46_50-Window](https://user-images.githubusercontent.com/14292619/99188054-f0c1d080-2751-11eb-9595-3a4a1b315041.png)
![2020-11-15 14_51_38-Window](https://user-images.githubusercontent.com/14292619/99188097-15b64380-2752-11eb-83a7-63908d1480e9.png)

My current work around is to not use MaxTo :/

**Comment by Spillmaker** [comment]
This happens for me with Discord and Explorer-windows.
Tested with turning Transparency off in both windows personality-settings and Maxto. Same issue...

It just simply seems that maxto is still setting transparency when moving the windows, and it fails to turn it off again after move is complete.

This in addition to a bunch of other small bugs just makes me want to start looking for other alternatives since this is a bug that has been for a long while, but only now resurfaced.

**Comment by mk7ita** [comment]
I have the same problem too sometimes, I didn't noticed problem with a specific software, it happens casually on all applications.

**Comment by eikowagenknecht** [comment]
Same problem here, also happens with Citrix Desktop. Turning **on** transparence fixes this, but I would prefer no transparence..

**Comment by KimmoJ** [comment]
This has happened to me a few times as well; currently, it's affecting the Firefox window I'm using to type this in. It happened when I dragged it from one screen to the other screen on a multi-screen computer, if that has any relevance. The window appears to be stuck transparent.

**Comment by vegardlarsen** [comment]
I have found the issue, and it only appears if "Window transparency" is turned off (which was why I didn't catch it in testing). It appears it does not check the settings at the point when we make a window transparent, but it was checked at the point when we make them opaque again, resulting in windows staying permanently transparent.

Work-around while I prepare 2.1.2: enable transparency. You can turn it off again after 2.1.2 ships. :)

Sorry about that!

**Comment by Michael5122** [comment]
> Guys!! Maxto is getting angry these days? What's going on? Now every time I move a window it reduces it in a small dimension
> 
> ![image](https://user-images.githubusercontent.com/65541736/99157032-11dcdf80-26c6-11eb-8a69-67e3ffe6d672.png)
> 
> Please help! 

Is it the same issue with this problem too?
Kind regards
Michail

**Comment by vegardlarsen** [comment]
@Michael5122 That issue is not related. Please open a separate issue for it. (PS! Make sure you can reproduce it consistently so I can have a look)

**Comment by vegardlarsen** [comment]
I've finished version 2.1.2, which fixes just this issue, and it should be visible on the website shortly, and be available for automatic updates at the same time.
