### ISSUE TITLE
cannot install new version of maxto

### ISSUE THREAD

**Issue by philipbroadhead** [digitalcreations/MaxTo#68]
![a0c18a83ee4c35f5a3455127d3a7bc1a](https://cloud.githubusercontent.com/assets/11799820/6994047/3723f3de-db02-11e4-9968-0049085ef420.png)

i get this error when trying to install the latest version of maxto.  the old version is uninstalled and the path that the error references does not exist!

**Comment by vegardlarsen** [comment]
@philipbroadhead Thanks for reporting this. Can you see what the installer was doing in the original installer window there?

**Comment by philipbroadhead** [comment]
yeah, it says it's "removing applications".

i've noticed that the path does create when running the installer and that MaxToSetup.msi file is in there.  but if i try to select it, it still gives me an error.

**Comment by philipbroadhead** [comment]
then it mentions that the old version of maxto could not be removed although i'm very much under the impression it has been removed :D

**Comment by philipbroadhead** [comment]
i just took some time to delete some stuff out of the registry and it's now installed fine.  thanks for getting back to me so quickly initially though :)

**Comment by vegardlarsen** [comment]
@philipbroadhead Good to hear. Let me know if you have any further problems.

**Comment by elmezie** [comment]
I am currently unable to remove MaxTo or install a new version of MaxTo in windows 10.  I receive the same error that the user received above.

**Comment by FLKaplan20271** [comment]
I have a similar problem.  I attempted to keep using 2.0 beta but it stopped working and continues to say, this application has stopped responding.  Ok, so I uninstalled and looked for an update.  I found one which was beta7.  I cannot install it.  It gave me an unhandled exception error during install.  I was ok, then I will clean the registry, reboot and try again - no go.  The installer does not even give a dialog window saying anything other than Do you want this application to make changes to your system maxto.core?  I don't have pictures right now because I have to work, but this is really annoying since I was using this to handle multiple applications on this screen.  Now everything is jumbled.  This happened when my UAC was enabled, then I went into the application and selected elevated permissions.  It flat out stopped working after that.

**Comment by vegardlarsen** [comment]
@FLKaplan20271 Can you try to get me the details of the "unhandled exception" during install? You can find descriptions for [how to get your log files here](https://maxto.net/documentation/troubleshooting).

**Comment by FLKaplan20271** [comment]
Unfortunately I have already attempted to remove it completely and reload -
now it will not install at all.  I still have build 1803 of Windows 10
because I have put off all of the updates but, as luck would have it, this
is before the October update and there are problems with the intermediate
updates between causing issues with installing other applications too.
There are no group policy objects. For all intents and purposes, this is my
work laptop and only has work stuff on it, but, I have full control over it.
-Frank
frank.kaplan@gmail.com

**Comment by vegardlarsen** [comment]
So if I understand you correctly you are having issues with other software installation on Windows as well?

The Squirrel log file would still be beneficial; it resides outside the MaxTo installation folder so you probably haven't removed it.

**Comment by FLKaplan20271** [comment]
Yes, it has to do with UAC.  I disabled it and the application installed
perfectly.  The other thing I checked when I started to have problems was
setting up elevation inside of the app.  As soon as I did that it stopped
working as I expected.
-Frank
frank.kaplan@gmail.com
