### ISSUE TITLE
Cannot get to change regions screen in multi-display setup

### ISSUE THREAD

**Issue by marklapasa** [digitalcreations/MaxTo#708]
**Describe the bug**

The app works fine on my Thnkpad X1 Carbon 1440p laptop on it's own. But when it's connected to 
1) 1440p monitor (portrait)
2) 4k monitor (landscape)
3) 1080p monitor (portrait)
all at once, it refuses to launch the screen where I can customize the regions

**To Reproduce**

1. In the system tray, right-click on MaxTo
2. Select Change Regions

**Expected behavior**

**Screenshots**
Screen furthest to the right is the 1440p laptop (landscape). The display is enabled and when MaxTo is launched, it makes it a black screen.
![image](https://user-images.githubusercontent.com/4932453/109051120-2f97e880-76a8-11eb-9028-d15cb1dfe478.png)

**System information:**
- Windows version: 
![image](https://user-images.githubusercontent.com/4932453/109051173-40485e80-76a8-11eb-91e6-31b17eb8ca10.png)

- MaxTo version: 
2.1.5

**Comment by marklapasa** [comment]
I tried to uninstall and re-install. Still, the issue persists. MaxTo Keyboard shortcuts like being able to center an active window the dead center (Win + Num 5) continue to work.

**Comment by marklapasa** [comment]
When I sign out and try to sign back in, MaxTo crashes. Attached here are the logs:

[maxto20210224.log](https://github.com/digitalcreations/MaxTo/files/6038251/maxto20210224.log)

**Comment by marklapasa** [comment]
The workaround until this issue is resolved:

1) Disable all the other displays except for the one you want to change the regions for
2) Perform "Change regions"
3) Re-enable all the other displays (e.g. Extend desktop)

**Comment by vegardlarsen** [comment]
According to the logs, you are experiencing the same crash as in #631. I did provide some suggestions there.

However, the fact that this seems to be caused by a specific monitor on your machine leaves me to think that there could be something about that monitor that turns black that is the problem. One thing I'd like to check (and I know that this may be difficult considering MaxTo crashes on you), is the detected serial numbers and location identifiers. You can find that when the "Change regions" window is open, by clicking "Monitor details". Then you can copy the details for each monitor for me here. I recommend you only have a single monitor enabled at a time when you do this.

**Comment by marklapasa** [comment]
@vegardlarsen here is the information you requested:

[ML: This is Lenovo Thinkpad X1 Carbon 6th Gen Laptop Display]
Friendly name: Wide viewing angle & High density FlexView Display 2560x1440
Device name: \\.\DISPLAY1
Location identifier: \{B82167EE-4DE7-11EB-AFA9-005056C00008}\0000
Serial number: 
DPI (dots per inch): 96×96
Resolution: 2560×1440 @ 0, 0
Working area: 2560×1400 @ 0, 0


[ML: This is a Benq ex2780q]
Friendly name: Generic PnP Monitor
Device name: \\.\DISPLAY4
Location identifier: \{B8216891-4DE7-11EB-AFA9-005056C00008}\0000
Serial number: 3AK00194019
DPI (dots per inch): 96×96
Resolution: 2560×1440 @ 0, 0
Working area: 2560×1400 @ 0, 0


Friendly name: Dell U4320Q (DP24K2K60)
Device name: \\.\DISPLAY5
Location identifier: \{B8216891-4DE7-11EB-AFA9-005056C00008}\0001
Serial number: 33LX223
DPI (dots per inch): 96×96
Resolution: 3840×2160 @ 0, 0
Working area: 3840×2120 @ 0, 0


Friendly name: DELL S2340L(Hdmi)
Device name: \\.\DISPLAY4
Location identifier: \{B8216891-4DE7-11EB-AFA9-005056C00008}\0000
Serial number: DGPV441A0KJT
DPI (dots per inch): 96×96
Resolution: 1920×1080 @ 0, 0
Working area: 1920×1040 @ 0, 0

**Comment by vegardlarsen** [comment]
Thanks for that. This could be coincidence caused by disconnecting and reconnecting the monitors; but there are two monitors with the same device name `\.\DISPLAY4`. I think we can safely assume that this is because the monitors get assigned new numbers when you disconnect other monitors.

What is less likely to be coincidence, however, is that both the built-in laptop display and the Dell S2340L seem to be sharing a location identifier: `{B8216891-4DE7-11EB-AFA9-005056C00008}\0000`. Because the built-in monitor does not provide a serial number (which is completely normal, as not all monitors report their serial number through EDID, which MaxTo reads), MaxTo will fall back to using the location identifier to identify the monitor. We could be running into trouble because those two monitors now share a location identifier.

There is a possibility this problem could be worked around by changing "Identify monitors by" to "Number" in MaxTo's settings (under Monitors). Can you please try and report back?

**Comment by marklapasa** [comment]
Went to Settings -> Monitor -> Then cycled thru Number, Properties and Serial Number.

Still the same outcome where I am unable to launch Change regions.

When I restart/signout+signin into Win10, MaxTo crashes, attached are the logs when "Properties" was last selected under Monitor.

[maxto20210228.log](https://github.com/digitalcreations/MaxTo/files/6057040/maxto20210228.log)

**Comment by vegardlarsen** [comment]
In the log files, you have a crash, identified by `UCEERR_RENDERTHREADFAILURE`. This seems to be related to video driver issues and WPF; we've seen this before in issue #631. That lead us to [an open bug in WPF](https://github.com/dotnet/wpf/issues/3100).

Can you please read through issue #631, and try out the suggestions listed there and report back?
