### ISSUE TITLE
Add a shortcut to extend a window on a adjacent region

### ISSUE THREAD

**Issue by turkian** [digitalcreations/MaxTo#71]
I'd like to extend a window easily whitout changing the layout.  If I have this layout with 4 regions and the window is in region B.

| A | B |
| --- | --- |
| C | D |

I'f like to select the window and extend it's border to cover region B and D.  It will add some flexibility on the layout.

**Comment by vegardlarsen** [comment]
@turkian Sorry, for the slow reply. What do you do when the regions don't line up exactly (which is 90% of the time).

Consider the case where you have 3 regions, one tall vertical one to the left, and two stacked on top of each other to the right. How would extending work then?

**Comment by zastrowm** [comment]
I might suggest having the feature be a sort of "Move window edge towards next region's edge in that direction". 

So for example, given this layout:
![image](https://cloud.githubusercontent.com/assets/3211021/7706788/0e662a2e-fe12-11e4-8340-1ec69a4e16b9.png)

 - moving a window in E *up* would move the top of the window to match the top of C.
 - moving a window in D *right* would move the right edge of the window to match the right of A.  Moving the window *right* again would move it to match the right side of E.

Obviously this is a feature I would also like to see implemented. My use case is I like to have "layers" of windows on certain monitors and I'd like to set up regions like below so that I can extend each window a little more than the one above it:

![image](https://cloud.githubusercontent.com/assets/3211021/7706889/96b3f5d2-fe12-11e4-8a9e-12f15d3f0967.png)

So in my case, I'd have 4 windows:

 - One in D
 - One in D and extends to C
 - One in D and extends to B
 - One in D and extends to A

**Comment by vegardlarsen** [comment]
This has been implemented in version 2.1.0 (currently in alpha).
