### ISSUE TITLE
Autostart of MaxTo not working both user accounts on same PC

### ISSUE THREAD

**Issue by JimboTh** [digitalcreations/MaxTo#767]
Hi,

Running a Win10 user account for myself and another for my wife on the 1 PC.

I installed on my account, then had to uninstall when it didn't appear on wife's account. Seemed to be OK when I installed on Wife's account. Not sure if this is not the recommended way to install on multiple accounts on 1 PC.

I inititally had autostart on my account, but noticed not autostarting on wife's account. When I configure my wife's account for autostart, it removes autostart on my acount etc.

Any suggestions?

Running Windows 10 Home on Surface Pro 7 with usb-c to LG49 monitor.

-Jim

**Comment by vegardlarsen** [comment]
Thank you for reporting this. This seems to be a bug.

I have verified that different users on the same machine share the same "namespace" when it comes to naming scheduled tasks. This means that if a user creates a scheduled task to start MaxTo at logon (this is what MaxTo does internally to enable it to start on logon), and names it "maxto", another user cannot create that same task.

At least not using the user interface. They can however create it programmatically (when MaxTo does it). The solution seems to be to use different names for the tasks per user; so instead of "maxto", we'll call it "maxto-jimbo" instead.

**Comment by vegardlarsen** [comment]
I've fixed this now, and it seems to work well. The changes will be in the next release.
