### ISSUE TITLE
Feature request: Limit browser fullscreen to a region

### ISSUE THREAD

**Issue by Zireael** [digitalcreations/MaxTo#768]
Hi,
Would it be possible to add a feature where an application enters "fullscreen mode" that is confined to a region rather than expanding to the entire screen?
For example, in Google Chrome browser, when you press F11, you enter a fullscreen mode. I want to limit that browser window to a specific region.
I want to use this to have several browser windows open without all the taskbars visible - just the pure webpage contents displayed side by side. The use case is to be able to display several stock market charts side by side with minimal wasted space between them.

Here's a (somewhat overdone) example of the desired effect:

![image](https://user-images.githubusercontent.com/3856578/135923997-cb326bc7-d8aa-4ec5-8a69-8bd12ee5b46c.png)

**Comment by ccc-dvansevenant** [comment]
+1 for this feature. I've tried several products, and this always seems to be the failing point. Setting up a nice 4-up grid on my big monitor, pulling up YouTube in one quad, then hitting `f` to go fullscreen in that quad, and boom! the entire monitor is taken up.

VDM by ishadow has managed it, but there is a compatibility issue with one of my apps. So, I'm still looking.

**Comment by vegardlarsen** [comment]
Thank you for reporting this. While I have no trouble seeing the usefulness of this, the feasibility of implementing it is however another matter entirely.

MaxTo works as well as it does because there exists "events" in Windows that we can listen to for intercepting when a window is maximized. Equivalent events do not exist for full-screen applications, mostly because there is no standardized way of running an application full screen.

This means there are a number of ways to actually achieve this full-screen effect, and it therefore gets very difficult to actually intercept them. Some of the methods (OpenGL/DirectX full screen) I don't think we can move safely.

At best, we would be able to force a few selected full screen applications into a region.

However, then comes the question of "which region". Triggering full-screen happens in a myriad of different ways (Alt+Enter, F11, double-click, clicking into a menu and selecting it), and we cannot rely on the cursor position to choose the region for the window. Since a full-screen window don't have a window title, we can't really move it to the other regions easily either.

So while this is a feature that I would very much like to get to work, the fact is that we wouldn't be able to do it in a good way.

**Comment by rsforbes** [comment]
This is an interesting comment because https://www.ishadow.com/ does just that. F11 and it contains it to the specific region.

**Comment by flyingwolf79** [comment]
> This is an interesting comment because https://www.ishadow.com/ does just that. F11 and it contains it to the specific region.

That is a nice program, but it looks like that and MaxTo are fundamentally different programs. 

MaxTo works on a per-monitor basis and as a handler to move and resize windows. 

The program you linked actually creates a number of virtual monitors, each with its own resolution and spatial location, and then overlays the locations on the existing physical hardware.

As such when you F11 a program in that software, it works as the program is under the impression that it is in fact hitting the full screen as it is being told that it is on a single monitor and it is now filling up that monitors space. 

MaxTo could possibly look into how this is handled and gain some inspiration from it. 

I can also see the two programs being extremely complementary to each other.
