### ISSUE TITLE
Unable to purchase MaxTo

### ISSUE THREAD

**Issue by KRNetworkSolutions** [digitalcreations/MaxTo#79]
Hello,

I have been trying to purchase several licenses off of the maxto.net website.  

I have been getting error below when trying to complete the purchase, can you please let us know when it will be resolved?

Thank you!

Error message:
Server Error in '/' Application.

Unable to sale

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: NetsSharp.Exceptions.BBSException: Unable to sale

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

**Comment by vegardlarsen** [comment]
Hi,

and thanks for writing. This is because of my shoddy implementation on the website, but there is actually a real error message behind here, it is just not shown on the website. In our backend, your issue is logged as "Refused by issuer".

My guess is that your card is not allowed for use outside your country, but it could be other causes as well.

I'll be working to provide better error messages in this case, and to figure out why some foreign cards are not allowed.

I am leaving this open as it is still a bug.

Best regards,
Vegard

**Comment by vegardlarsen** [comment]
This is now in production and hopefully no-one will ever see this again. ;)
