### ISSUE TITLE
IS THIS APP STILL UNDER DEVELOPMENT??

### ISSUE THREAD

**Issue by TheSQLGuru** [digitalcreations/MaxTo#808]
IS THIS APP STILL UNDER DEVELOPMENT?

**Comment by MalteHillmann** [comment]
The last release was almost 2 years ago. I think they stopped development.

**Comment by crawt** [comment]
@vegardlarsen can u give me more informations?

**Comment by ringhofd** [comment]
Unfortunately MaxTo seems to have become abandonware.

**Comment by vegardlarsen** [comment]
We are still here supporting it. We are aware that there has not been many updates recently, and we are sorry about that. If we cease supporting it, then we will let you know.

Unfortunately, my attention is diverted elsewhere recently, which is why I have not been able to respond in a timely manner.
