### ISSUE TITLE
i can not install the program______

### ISSUE THREAD

**Issue by martonkliniken** [digitalcreations/MaxTo#811]
**Describe the bug**

**To Reproduce**

1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**System information:**
- Windows version: 
- MaxTo version: 

**Additional context**

**Comment by vegardlarsen** [comment]
This is unfortunately a known problem with our installer. What usually happens is that you either run the installer twice, which is easily done because the installer does not present a user interface and it can take quite a while before MaxTo is running, or because you ran the installer when MaxTo was already running.

In most cases, MaxTo will already be installed on your computer. You can search for MaxTo on the Start menu, or see if it is already running in the notification area (next to the clock on the task bar). It may sometimes "hide" behind the small up arrow.

If MaxTo isn't installed properly on your computer, you may have to take the following steps:

1. Uninstall MaxTo from "Add or remove programs".
2. Reboot the computer. This step is required to ensure that MaxTo is completely unloaded.
3. Install MaxTo again, making sure you only run the installer once.
